/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Metodos.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author zlaifer
 */
public class F_CambiarContrasena extends javax.swing.JInternalFrame {

    Conexion Con = new Conexion();
    Connection Conectar = Con.Conexion();
    Statement Sent;
    public F_CambiarContrasena() {
        initComponents();
        ObtnerUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel42 = new javax.swing.JLabel();
        JT_PassA = new javax.swing.JPasswordField();
        jLabel44 = new javax.swing.JLabel();
        JT_PassN = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        JT_PassNr = new javax.swing.JPasswordField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(393, 233));
        setPreferredSize(new java.awt.Dimension(393, 233));
        getContentPane().setLayout(null);

        jLabel42.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel42.setText("CONTRASEÑA ANTIGUA");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(30, 50, 180, 30);

        JT_PassA.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        JT_PassA.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(JT_PassA);
        JT_PassA.setBounds(200, 50, 160, 30);

        jLabel44.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel44.setText("CONTRASEÑA NUEVA");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(30, 80, 150, 30);

        JT_PassN.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        JT_PassN.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(255, 255, 255)));
        JT_PassN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_PassNActionPerformed(evt);
            }
        });
        JT_PassN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JT_PassNKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JT_PassNKeyTyped(evt);
            }
        });
        getContentPane().add(JT_PassN);
        JT_PassN.setBounds(200, 80, 160, 30);

        jLabel41.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel41.setText("NUEVAMENTE");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(30, 110, 100, 30);

        JT_PassNr.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        JT_PassNr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(JT_PassNr);
        JT_PassNr.setBounds(200, 110, 160, 30);

        jButton8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton8.setText("ACEPTAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(130, 150, 110, 30);

        jButton9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton9.setText("SALIR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(240, 150, 110, 30);

        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CAMBIAR CONTRASEÑA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 0, 360, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JT_PassNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_PassNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_PassNActionPerformed

    private void JT_PassNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JT_PassNKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_PassNKeyReleased

    private void JT_PassNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JT_PassNKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_PassNKeyTyped

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        CambiarPass();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Limpiar();
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed
 void CambiarPass() {

        String PassN = JT_PassN.getText();
        String PassNr = JT_PassNr.getText();

        if (PassN.equals(PassNr)) {

            String sql = "update usuario set contrasena=? where nickname='" + F_Loggin.CapturarNickname + "' && contrasena='" + JT_PassA.getText() + "'";

            try {
                PreparedStatement ps = Conectar.prepareStatement(sql);

                ps.setString(1, JT_PassN.getText());

                int n = ps.executeUpdate();//valida si se guardaron los datos; si pst>0 entonces se guardaron

                JOptionPane.showMessageDialog(null, "Contraseña Actualizada Correctamente");
                Limpiar();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error Al Modificar La Contraseña", "Modificar ", JOptionPane.ERROR_MESSAGE);

            }

        } else {

            JOptionPane.showMessageDialog(this, "Verifique Que Los Campos Contraseña Coincidan", "Error", JOptionPane.ERROR_MESSAGE);
//            JOptionPane.showMessageDialog(null, "Contraseña Nueva: "+PassN+"\n Nuevamente: "+PassNr+"\n Contraseña Antigua: "+Pass);

        }

    }
     void ObtnerUsuario() {

        String sql = "select nickname,contrasena from usuario where nickname='" + F_Loggin.CapturarNickname + "'";

        try {

            com.mysql.jdbc.Statement st = (com.mysql.jdbc.Statement) Conectar.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                String Pass = rs.getString("contrasena");
                JT_PassA.setEnabled(false);
                JT_PassA.setText(Pass);
            }
        } catch (Exception e) {

            System.out.println("Error En El Metodo Obtener Usuario");
        }

    }
 void Limpiar() {

        JT_PassN.setText("");
        JT_PassNr.setText("");
        //JT_PassA.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JT_PassA;
    private javax.swing.JTextField JT_PassN;
    private javax.swing.JPasswordField JT_PassNr;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
