/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Metodos.Conexion;
import Metodos.MetodosGenerales;
import Metodos.MetodosJasper;
import Modelos.Modelo_Cliente;
import Modelos.Modelo_CodigoPostal;
import Modelos.Modelo_Poblacion;
import Modelos.Modelo_Provincia;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author zlaifer
 */
public class F_Clientes extends javax.swing.JInternalFrame {

    MetodosGenerales m = new MetodosGenerales();
    Modelo_Cliente mE = new Modelo_Cliente();
    Modelo_CodigoPostal cp = new Modelo_CodigoPostal();
    Modelo_Provincia pro = new Modelo_Provincia();
    Modelo_Poblacion pob = new Modelo_Poblacion();
    String SentenciaSql = null;
    String TablaSql = "cliente";
    String TablasSql = "cliente,codigo_postal,poblacion,provincia";
    String FiltroSql = null;
    int BanderaValidarCombos = 0;
    //-----jasper report
    Conexion Con = new Conexion();
    Connection Conectar = Con.Conexion();

    JasperReport Jr = null;
    JasperPrint Jp = null;
    JasperViewer Jv = null;

    public F_Clientes() {
        initComponents();

        Listar();
        DesHabilitar();
        ValidarCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField9 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        JT_IdCodPostal = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jTextField13 = new javax.swing.JTextField();
        JT_IdPoblacion = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField17 = new javax.swing.JTextField();
        JT_IdProvincia = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTB_Auxiliar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setResizable(true);
        setMinimumSize(new java.awt.Dimension(1019, 389));
        setPreferredSize(new java.awt.Dimension(1019, 389));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("EMAIL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 100, 80, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("IDENTIFICACION");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 110, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("DIRECCION");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 40, 90, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("NOMBRE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 100, 80, 30);

        jTextField7.setToolTipText("Puedes Buscar Por Identificacion Del Cliente O Por Nombre Del Cliente");
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(70, 150, 780, 30);

        jTextField11.setEditable(false);
        jTextField11.setFocusable(false);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(150, 40, 150, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- SELECCIONE UNO---", "CEDULA CIUDADANIA", "CEDULA EXTRANJERIA", "NIT", " " }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(150, 40, 170, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("PROVINCIA");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(600, 100, 110, 30);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Buscar");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 150, 60, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("COD POSTAL");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(600, 40, 80, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setFocusable(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 180, 830, 150);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.setToolTipText("Salir De Esta Ventana");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(870, 280, 110, 30);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("REPORTE");
        jButton3.setToolTipText("Imprimir Datos De La Tabla");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(870, 50, 110, 30);

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("EXPORTAR");
        jButton4.setToolTipText("Exportar Datos De  La Tabla");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(870, 80, 110, 30);

        jButton5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton5.setText("CREAR");
        jButton5.setToolTipText("Crear Nuevo Trabajador");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(870, 130, 110, 30);

        jButton6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton6.setText("CANCELAR");
        jButton6.setToolTipText("Cancelar ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(870, 220, 110, 30);

        jButton7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton7.setText("MODIFICAR");
        jButton7.setToolTipText("Modificar Datos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(870, 190, 110, 30);

        jButton8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton8.setText("ELIMINAR");
        jButton8.setToolTipText("Eliminar Datos");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(870, 250, 110, 30);

        jButton9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton9.setText("GRABAR");
        jButton9.setToolTipText("Guardar Datos");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(870, 160, 110, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(860, 60, 10, 240);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(150, 70, 170, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(150, 100, 170, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("TIPO IDENTIFICACION");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 40, 130, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("TELEFONO");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(330, 70, 110, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("POBLACION");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(600, 70, 110, 30);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(410, 100, 180, 30);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(410, 40, 180, 30);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(410, 70, 180, 30);

        jTextField16.setEditable(false);
        jTextField16.setFocusable(false);
        getContentPane().add(jTextField16);
        jTextField16.setBounds(690, 70, 140, 30);

        JT_IdCodPostal.setEditable(false);
        JT_IdCodPostal.setFocusable(false);
        getContentPane().add(JT_IdCodPostal);
        JT_IdCodPostal.setBounds(690, 70, 50, 30);

        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(690, 70, 160, 30);

        jTextField13.setEditable(false);
        jTextField13.setFocusable(false);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(690, 40, 140, 30);

        JT_IdPoblacion.setEditable(false);
        JT_IdPoblacion.setFocusable(false);
        getContentPane().add(JT_IdPoblacion);
        JT_IdPoblacion.setBounds(690, 40, 50, 30);

        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(690, 40, 160, 30);

        jTextField17.setEditable(false);
        jTextField17.setFocusable(false);
        getContentPane().add(jTextField17);
        jTextField17.setBounds(690, 100, 140, 30);

        JT_IdProvincia.setEditable(false);
        JT_IdProvincia.setFocusable(false);
        getContentPane().add(JT_IdProvincia);
        JT_IdProvincia.setBounds(690, 100, 40, 30);

        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(690, 100, 160, 30);

        JTB_Auxiliar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTB_Auxiliar.setFocusable(false);
        jScrollPane2.setViewportView(JTB_Auxiliar);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 450, 840, 80);

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLIENTES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Cambria", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 980, 340);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(50, 140, 780, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        ValidarCampos();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        BanderaValidarCombos = 1;
        ValidarCombos();
        Habilitar();
        jTextField11.transferFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

        HabilitarTabla();
        ObtenerDatosTabla();

    }//GEN-LAST:event_jTable1MousePressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        DesHabilitar();
        Limpiar();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        Listar();
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        Modificar();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Eliminar();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String Combo = jComboBox1.getSelectedItem().toString();
        if (Combo.equals("CEDULA CIUDADANIA")) {
            jTextField11.setText("C.C");
        }
        if (Combo.equals("CEDULA EXTRANJERIA")) {
            jTextField11.setText("C.E");
        }
        if (Combo.equals("NIT")) {
            jTextField11.setText("NIT");
        }

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged

        ObtenerPoblacion();
        CargarComboProvincia();

    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged

        ObtenerCodigoPostal();
        CargarComboPoblacion();
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
        ObtenerProvincia();
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        MetodosJasper Mj = new MetodosJasper();

        int i = JOptionPane.showConfirmDialog(null, "¿Desea Generar Reporte?", "Reporte", JOptionPane.YES_NO_OPTION);

        if (i == JOptionPane.YES_OPTION) {

            if (jTextField9.getText().equals("")) {
                
                Mj.CrearReporte("C:\\TesoCartera\\src\\Reportes\\Report_Clientes.jasper", null, null);
                Mj.VisualizarReporte();
            } else {
                Mj.CrearReporte("C:\\TesoCartera\\src\\Reportes\\Report_Cliente.jasper", "id_cliente", jTextField9.getText());
                Mj.VisualizarReporte();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

//-----------------------------------
//    void CrearReporte() {
//
//        String RutaReporte = "C:\\TesoCartera\\src\\Reportes\\ReportesClientes.jasper";
//
//        try {
//
////            Map parametro = new HashMap();
////            parametro.put("id_cliente", jTextField9.getText());
////            Jr = JasperCompileManager.compileReport(RutaReporte);
////            Jp = JasperFillManager.fillReport(Jr, parametro, Conectar);
////            Jv = new JasperViewer(Jp);
////            Jv.setVisible(true);
////            Jv.setTitle("Reporte Cliente");
//            Jr = (JasperReport) JRLoader.loadObjectFromFile(RutaReporte);
//            Jp = JasperFillManager.fillReport(Jr, null, Conectar);
//
//        } catch (JRException e) {
//            JOptionPane.showMessageDialog(this, "Error En Ejecucion De Jasper: " + e);
//        }
//
//    }
//
//    void VisualizarReporte() {
//
//        Jv = new JasperViewer(Jp);
//        Jv.setVisible(true);
//        Jv.setTitle("Reporte Cliente");
//    }
//----------------------------------
    void ValidarCampos() {
        if (!jTextField11.getText().equals("") && !jTextField9.getText().equals("") && !jTextField4.getText().equals("") && !jTextField15.getText().equals("")
                && !jTextField4.getText().equals("") && !jTextField8.getText().equals("") && !jTextField9.getText().equals("") && !jTextField15.getText().equals("")
                && !jTextField8.getText().equals("") && !jTextField10.getText().equals("") && !jTextField13.getText().equals("") && !jTextField17.getText().equals("")) {
            Grabar();
        } else {
            JOptionPane.showMessageDialog(this, "Verifique Que Ningun Campo Este Vacio", "Verificar", JOptionPane.ERROR_MESSAGE);
        }
    }

    //-------------------------------------------------
    void ValidarCombos() {

        if (BanderaValidarCombos == 1) {

            CargarComboCodPostal();
        } else {

            System.out.println("Bandera igual a 0");
        }
    }
//--------------Metodos--------------

    void Listar() {
        FiltroSql = jTextField7.getText();
        String Sql = "select cliente.id_cliente,cliente.tipo_identificacion,cliente.nombre_cliente,cliente.direccion_cliente,"
                + "cliente.telefono_cliente,cliente.email_cliente,codigo_postal.nombre_pais,poblacion.nombre_poblacion,"
                + "provincia.nombre_provincia from " + TablasSql + ""
                + " where cliente.id_cod_postal=codigo_postal.id_cod_postal && cliente.id_poblacion_cliente=poblacion.id_poblacion &&"
                + " cliente.id_provincia_cliente=provincia.id_provincia && concat(cliente.id_cliente,cliente.nombre_cliente) like '%" + FiltroSql + "%'"
                + " order by cliente.nombre_cliente asc";
        m.Listar(Sql, jTable1);

        ListarAuxiliar();
    }

    void ListarAuxiliar() {
        FiltroSql = jTextField7.getText();
        String Sql = "select * from " + TablaSql + " where concat(id_cliente,nombre_cliente) like '%" + FiltroSql + "%'"
                + " order by nombre_cliente asc";
        m.Listar(Sql, JTB_Auxiliar);

    }
//--------------

    void Grabar() {

        mE.setIdCliente(jTextField9.getText());
        mE.setTipoIdentificacion(jTextField11.getText());
        mE.setNombreCliente(jTextField4.getText());
        mE.setDireccion(jTextField15.getText());
        mE.setIdCodPostal(JT_IdCodPostal.getText());
        mE.setIdPoblacion(JT_IdPoblacion.getText());
        mE.setIdProvincia(JT_IdProvincia.getText());
        mE.setTelefonos(jTextField8.getText());
        mE.setEmail(jTextField10.getText());

        SentenciaSql = "'" + mE.getIdCliente() + "','" + mE.getTipoIdentificacion() + "','" + mE.getNombreCliente() + "','" + mE.getDireccion()
                + "','" + mE.getTelefonos() + "','" + mE.getEmail() + "','" + mE.getIdCodPostal() + "','"
                + mE.getIdPoblacion() + "','" + mE.getIdProvincia() + "'";

        m.Grabar(TablaSql, SentenciaSql);
        Limpiar();
        Listar();
//        Desabilitar();
    }

    void Modificar() {

        mE.setIdCliente(jTextField9.getText());
        mE.setTipoIdentificacion(jTextField11.getText());
        mE.setNombreCliente(jTextField4.getText());
        mE.setDireccion(jTextField15.getText());
        mE.setIdCodPostal(JT_IdCodPostal.getText());
        mE.setIdPoblacion(JT_IdPoblacion.getText());
        mE.setIdProvincia(JT_IdProvincia.getText());
        mE.setTelefonos(jTextField8.getText());
        mE.setEmail(jTextField10.getText());

        SentenciaSql = "nombre_cliente='" + mE.getNombreCliente() + "',tipo_identificacion='" + mE.getTipoIdentificacion() + "', direccion_cliente='" + mE.getDireccion()
                + "', id_cod_postal='" + mE.getIdCodPostal() + "',id_poblacion_cliente='" + mE.getIdPoblacion() + "' ,id_provincia_cliente='" + mE.getIdProvincia() + "' ,telefono_cliente='"
                + mE.getTelefonos() + "' ,email_cliente='" + mE.getEmail() + "' where id_cliente='" + mE.getIdCliente() + "'";

        System.out.println("Sql: " + SentenciaSql);
        m.Modificar(TablaSql, SentenciaSql);
        Limpiar();
        Listar();

    }

    void Eliminar() {
        mE.setIdCliente(jTextField9.getText());
        SentenciaSql = "id_cliente = " + mE.getIdCliente();
        m.Eliminar(TablaSql, SentenciaSql);

        Limpiar();
        Listar();

    }
//-------------- 

    void Limpiar() {
        m.LimpiarJText(JT_IdCodPostal);
        m.LimpiarJText(JT_IdPoblacion);
        m.LimpiarJText(JT_IdProvincia);
        m.LimpiarJText(jTextField4);
        m.LimpiarJText(jTextField7);
        m.LimpiarJText(jTextField8);
        m.LimpiarJText(jTextField9);
        m.LimpiarJText(jTextField10);
        m.LimpiarJText(jTextField11);
        m.LimpiarJText(jTextField15);
        m.LimpiarJText(jTextField16);
        m.LimpiarJText(jTextField13);
        m.LimpiarJText(jTextField17);

    }

    void Habilitar() {

        m.HabilitarJText(jTextField9);
        m.HabilitarJText(jTextField4);
        m.HabilitarJText(jTextField15);
        m.HabilitarJText(jTextField8);
        m.HabilitarJText(jTextField10);
        m.HabilitarJCombo(jComboBox1);
        m.HabilitarJCombo(jComboBox4);
        m.HabilitarJCombo(jComboBox3);
        m.HabilitarJCombo(jComboBox5);

        m.DesHabilitarJBtn(jButton5);
        m.HabilitarJBtn(jButton9);
        m.DesHabilitarJBtn(jButton7);
        m.HabilitarJBtn(jButton6);
        m.DesHabilitarJBtn(jButton8);
    }

    void HabilitarTabla() {

        m.HabilitarJText(jTextField9);
        m.HabilitarJText(jTextField4);
        m.HabilitarJText(jTextField15);
        m.HabilitarJText(jTextField8);
        m.HabilitarJText(jTextField10);
        m.HabilitarJCombo(jComboBox1);
        m.HabilitarJCombo(jComboBox4);
        m.HabilitarJCombo(jComboBox3);
        m.HabilitarJCombo(jComboBox5);

        m.HabilitarJBtn(jButton5);
        m.DesHabilitarJBtn(jButton9);
        m.HabilitarJBtn(jButton7);
        m.HabilitarJBtn(jButton6);
        m.HabilitarJBtn(jButton8);
    }

    void DesHabilitar() {

        m.DesHabilitarJText(jTextField9);
        m.DesHabilitarJText(jTextField4);
        m.DesHabilitarJText(jTextField15);
        m.DesHabilitarJText(jTextField8);
        m.DesHabilitarJText(jTextField10);
        m.DesHabilitarJCombo(jComboBox1);
        m.DesHabilitarJCombo(jComboBox4);
        m.DesHabilitarJCombo(jComboBox3);
        m.DesHabilitarJCombo(jComboBox5);

        m.HabilitarJBtn(jButton5);
        m.DesHabilitarJBtn(jButton9);
        m.DesHabilitarJBtn(jButton7);
        m.DesHabilitarJBtn(jButton6);
        m.DesHabilitarJBtn(jButton8);
    }
//---------------    

    void CargarComboCodPostal() {

        try {
            String Sql = "select * from codigo_postal";
            String IdSql = "id_cod_postal";
            String NombreSql = "nombre_pais";

            m.CargarLIstaComboBox(Sql, IdSql, NombreSql, "]", jComboBox3);
        } catch (Exception e) {
            System.out.println("Error cargar combopostal");
        }

    }

    void ObtenerCodigoPostal() {

        try {
            String Delimitador = "]";
            String Aux = (String) jComboBox3.getSelectedItem();
            String[] Separacion = Aux.split(Delimitador);
            jTextField13.setText(Separacion[1]);
            JT_IdCodPostal.setText(Separacion[0]);
        } catch (Exception e) {

            System.out.println("Error obtenercodigopostal");
            jTextField13.setText("");
            JT_IdCodPostal.setText("");
        }

    }

    void CargarComboPoblacion() {

        try {
            String Sql = "select * from poblacion where id_codigo_postal='" + JT_IdCodPostal.getText() + "'";
            String IdSql = "id_poblacion";
            String NombreSql = "nombre_poblacion";

            m.CargarLIstaComboBox(Sql, IdSql, NombreSql, "]", jComboBox4);
        } catch (Exception e) {

            System.out.println("Error cargar combo poblacion");
            jComboBox4.removeAllItems();
            jTextField16.setText("");
            JT_IdPoblacion.setText("");
        }
        //ObtenerPoblacion();
    }

    void ObtenerPoblacion() {

        String Delimitador = "]";
        String Aux = (String) jComboBox4.getSelectedItem();

        try {

            String[] Separacion = Aux.split(Delimitador);
            jTextField16.setText(Separacion[1]);
            JT_IdPoblacion.setText(Separacion[0]);
        } catch (Exception e) {
            jTextField16.setText("");
            JT_IdPoblacion.setText("");
        }

    }

    void CargarComboProvincia() {

        try {
            String Sql = "select * from provincia where id_poblacion='" + JT_IdPoblacion.getText() + "'";
            String IdSql = "id_provincia";
            String NombreSql = "nombre_provincia";

            m.CargarLIstaComboBox(Sql, IdSql, NombreSql, "]", jComboBox5);
        } catch (Exception e) {
            System.out.println("Error cargar combo provincia");
            jComboBox5.removeAllItems();
            jTextField17.setText("");
            JT_IdProvincia.setText("");

        }

        // ObtenerProvincia();
    }

    void ObtenerProvincia() {
        try {
            String Delimitador = "]";
            String Aux = (String) jComboBox5.getSelectedItem();
            String[] Separacion = Aux.split(Delimitador);
            jTextField17.setText(Separacion[1]);
            JT_IdProvincia.setText(Separacion[0]);
        } catch (Exception e) {
            jTextField17.setText("");
            JT_IdProvincia.setText("");
        }

    }

    //------------------
    void ObtenerDatosTabla() {
        int Fila = jTable1.getSelectedRow();

        m.ObtenerDatoTabla(jTable1, Fila, jTextField9, 0);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField11, 1);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField4, 2);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField15, 3);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField8, 4);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField10, 5);
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, JT_IdCodPostal, 6);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField13, 6);
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, JT_IdPoblacion, 7);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField16, 7);
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, JT_IdProvincia, 8);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField17, 8);

    }
    //------------------------------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTB_Auxiliar;
    private javax.swing.JTextField JT_IdCodPostal;
    private javax.swing.JTextField JT_IdPoblacion;
    private javax.swing.JTextField JT_IdProvincia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
