/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import static Frames.F_Factura.JL_Consecutivo;
import Metodos.Conexion;
import Metodos.MetodosGenerales;
import Modelos.Modelo_CodigoPostal;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author zlaifer
 */
public class F_CodPostal extends javax.swing.JInternalFrame {

    Metodos.MetodosGenerales m = new MetodosGenerales();
    Modelos.Modelo_CodigoPostal mcp = new Modelo_CodigoPostal();
    boolean BanderaNuevo = false;
    String FiltroSql, SentenciaSql;
    String TablaSql = "codigo_postal";
    //---------------Jasper Report
    Conexion Con = new Conexion();
    Connection Conectar = Con.Conexion();
    JasperReport Jr = null;
    JasperPrint Jp = null;
    JasperViewer Jv = null;
    String Patch = "";

    public F_CodPostal() {
        initComponents();
        ValidarBanderaBtnNuevo();
        DesHabilitar();
        Listar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setMinimumSize(new java.awt.Dimension(618, 307));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(618, 307));
        getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("REPORTE");
        jButton3.setToolTipText("Imprimir Datos De La Tabla");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(470, 40, 110, 30);

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("EXPORTAR");
        jButton4.setToolTipText("Exportar Datos De  La Tabla");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(470, 70, 110, 30);

        jButton10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton10.setText("NUEVO");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(470, 100, 110, 30);

        jButton11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton11.setText("MODIFICAR");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(470, 130, 110, 30);

        jButton12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton12.setText("CANCELAR");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(470, 160, 110, 30);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(470, 190, 110, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.setToolTipText("Salir De Esta Ventana");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 220, 110, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("CODIGO  POSTAL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 40, 130, 30);

        jTextField1.setEditable(false);
        jTextField1.setFocusable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 40, 80, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("PAIS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 40, 50, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(270, 40, 180, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 430, 130);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(460, 40, 20, 210);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("BUSCAR");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 90, 90, 30);

        jTextField8.setToolTipText("Puedes Buscar Por Identificacion Del Codigo Postal O Por Nombre Del Pais");
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(80, 90, 370, 30);

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CODIGO POSTAL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 580, 260);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(30, 80, 410, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "¿Desea Generar Reporte?", "Reporte", JOptionPane.YES_NO_OPTION);

        if (i == JOptionPane.YES_OPTION) {

            CrearReporte();
            VisualizarReporte();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        String AuxBtn = jButton10.getText();
        if (AuxBtn.equals("NUEVO")) {
            BanderaNuevo = true;
            Habilitar();

        } else {
            BanderaNuevo = false;
            DesHabilitar();
        }

//        Limpiar();
//        Habilitar();
        ComprobarBtn();

        ValidarBanderaBtnNuevo();

        //        Grabar();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Modificar();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Limpiar();
        DesHabilitar();
        BanderaNuevo = false;
        ValidarBanderaBtnNuevo();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Eliminar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        Listar();
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        ObtenerDatosTabla();
        HabilitarTabla();
    }//GEN-LAST:event_jTable1MousePressed

    //--------------METODOS JASPER
    public void CrearReporte() {

        Patch = "C:\\TesoCartera\\src\\Reportes\\Report_CodigoPostal.jasper";
        try {

            Jr = (JasperReport) JRLoader.loadObjectFromFile(Patch);
            Jp = JasperFillManager.fillReport(Jr, null, Conectar);

        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Error En Ejecucion De Jasper: " + e);
        }
    }

    public void VisualizarReporte() {

        Jv = new JasperViewer(Jp, false);
        Jv.setVisible(true);
        Jv.setTitle("PAISES REGISTRADOS");
    }

    //--------------------------------

    void ValidarBanderaBtnNuevo() {

        if (BanderaNuevo == false) {
            jButton10.setText("NUEVO");
        } else {
            jButton10.setText("GRABAR");
        }

    }

    void ComprobarBtn() {

        String Aux = jButton10.getText();

        if (Aux.equals("NUEVO")) {

            Limpiar();
            ObtenerConsecutivo();
        } else {

            if (!jTextField2.getText().equals("")) {
                Grabar();
            } else {
                JOptionPane.showMessageDialog(this, "Verifique Que El Campo Pais No Este Vacio", "Verificar", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    void Grabar() {

        mcp.setIdCodPostal(Integer.parseInt(jTextField1.getText()));
        mcp.setNombrePais(jTextField2.getText());

        SentenciaSql = "'" + mcp.getIdCodPostal() + "' , '" + mcp.getNombrePais() + "'";
        m.Grabar(TablaSql, SentenciaSql);

        Limpiar();
        Listar();

    }

    void Modificar() {
        mcp.setIdCodPostal(Integer.parseInt(jTextField1.getText()));
        mcp.setNombrePais(jTextField2.getText());

        SentenciaSql = "nombre_pais='" + mcp.getNombrePais() + "' where id_cod_postal='" + mcp.getIdCodPostal() + "'";
        m.Modificar(TablaSql, SentenciaSql);
        Limpiar();
        Listar();
    }

    void Eliminar() {
        mcp.setIdCodPostal(Integer.parseInt(jTextField1.getText()));
        SentenciaSql = "id_cod_postal = '" + mcp.getIdCodPostal() + "'";

        System.out.println("id = " + mcp.getIdCodPostal());
        m.Eliminar(TablaSql, SentenciaSql);
        Limpiar();
        Listar();
    }

    void Listar() {
        FiltroSql = jTextField8.getText();
        String Sql = "select * from " + TablaSql + " where concat(id_cod_postal,nombre_pais) like '%" + FiltroSql + "%'"
                + " order by id_cod_postal asc";
        m.Listar(Sql, jTable1);

    }

    void Limpiar() {

        m.LimpiarJText(jTextField1);
        m.LimpiarJText(jTextField2);
        m.LimpiarJText(jTextField8);
    }

    void ObtenerConsecutivo() {

        m.ObtenerConsecutivo("codigo_postal", "id_cod_postal", jTextField1);
    }

    void ObtenerDatosTabla() {
        int Fila = jTable1.getSelectedRow();
        m.ObtenerDatoTabla(jTable1, Fila, jTextField1, 0);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField2, 1);
    }

    void Habilitar() {

        m.HabilitarJText(jTextField2);
        //m.DesHabilitarJBtn(jButton10);
        m.DesHabilitarJBtn(jButton11);
        m.HabilitarJBtn(jButton12);
        m.DesHabilitarJBtn(jButton2);
        m.HabilitarJBtn(jButton1);
        jTextField1.transferFocus();

    }

    void HabilitarTabla() {

        BanderaNuevo = false;
        ValidarBanderaBtnNuevo();
        m.HabilitarJText(jTextField2);
        //m.DesHabilitarJBtn(jButton10);
        m.HabilitarJBtn(jButton11);
        m.HabilitarJBtn(jButton12);
        m.HabilitarJBtn(jButton2);
        m.HabilitarJBtn(jButton1);
        jTextField1.transferFocus();

    }

    void DesHabilitar() {

        jTextField1.transferFocus();
        m.DesHabilitarJText(jTextField2);
        //m.DesHabilitarJBtn(jButton10);
        m.DesHabilitarJBtn(jButton11);
        m.DesHabilitarJBtn(jButton12);
        m.DesHabilitarJBtn(jButton2);
        m.HabilitarJBtn(jButton1);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
