/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Metodos.MetodosGenerales;

/**
 *
 * @author zlaifer
 */
public class F_ConsultaProductos extends javax.swing.JInternalFrame {

    MetodosGenerales m = new MetodosGenerales();
    String TablaSql = "producto";
    String SentenciaSql;

    public F_ConsultaProductos() {
        initComponents();
        ValidarFiltrar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(949, 490));
        setPreferredSize(new java.awt.Dimension(949, 490));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("XXX");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 390, 150, 30);

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Si" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(90, 60, 70, 30);

        jComboBox2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Seleccione Uno --", "Identificacion", "Tipo De Identificacion", "Apellidos", "Codigo Postal", "Poblacion", "Provincia", "Direccion", "Telefono", "Email", "Nickname", "Tipo De Usuario", "Fecha De Registro" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(450, 60, 210, 30);

        jComboBox3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Seleccione Uno --", "Identificacion Producto", "Codigo De Barras", "Referencia De Producto", "Referencia De Producto-Cliente", "Descripcion De Producto", "Categoria De Producto", "Unidad De Medidad", "Stock Actual Mayor A", "Stock Actual Menor A", "Precio De Producto Mayor A", "Precio De Producto Menor A", "Precio De Venta Mayor A", "Precio De Venta Menor A" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(220, 60, 210, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(50, 100, 820, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setFocusable(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 890, 270);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(450, 60, 210, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/consulta.png"))); // NOI18N
        jButton1.setText("CONSULTAR");
        jButton1.setToolTipText("Salir De Esta Ventana");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(650, 390, 130, 40);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("SALIR");
        jButton2.setToolTipText("Salir De Esta Ventana");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(780, 390, 120, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("FILTRAR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 60, 80, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("TOTAL PRODUCTOS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 390, 150, 30);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(640, 60, 140, 30);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(450, 60, 140, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("A");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(610, 60, 30, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("TIPO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 60, 80, 30);

        jTextField15.setEditable(false);
        jTextField15.setFocusable(false);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(320, 510, 150, 20);

        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUCTOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 10, 910, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Consultar();
        ConteoTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        ValidarFiltrar();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        ValidarTipo();
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged

        String Aux = jComboBox3.getSelectedItem().toString();

        if (Aux == "Categoria De Producto") {
            ObtenerCategoriaProducto();
        }
        if (Aux == "Unidad De Medidad") {
            ObtenerUnidadMedida();
        }


    }//GEN-LAST:event_jComboBox2ItemStateChanged

    void ValidarFiltrar() {

        String Aux = jComboBox1.getSelectedItem().toString();
        if (Aux == "No") {
            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(false);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            Consultar();

        } else {

            jLabel5.setVisible(true);
            jComboBox3.setVisible(true);
//            ValidarTipo();
        }

    }

    void ValidarTipo() {

        String Tipo = jComboBox3.getSelectedItem().toString();

        if (Tipo == "Identificacion Producto") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            //jComboBox3.transferFocus();
        }
        if (Tipo == "Codigo De Barras") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            //jComboBox3.transferFocus();
        }
        if (Tipo == "Referencia De Producto") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            //jComboBox3.transferFocus();
        }
        if (Tipo == "Referencia De Producto-Cliente") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            //jComboBox3.transferFocus();
        }
        if (Tipo == "Descripcion De Producto") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            //jComboBox3.transferFocus();
        }
        if (Tipo == "Categoria De Producto") {

//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(true);
            LlenarComboCateogriaProducto();
            jTextField1.setVisible(false);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            //jComboBox3.transferFocus();

        }
        if (Tipo == "Unidad De Medidad") {

//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(true);
            LlenarComboUnidadMedida();
            jTextField1.setVisible(false);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            //jComboBox3.transferFocus();

        }
        if (Tipo == "Stock Actual Mayor A") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            //jComboBox3.transferFocus();
        }
        if (Tipo == "Stock Actual Menor A") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            //jComboBox3.transferFocus();
        }
        if (Tipo == "Precio De Producto Mayor A") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            //jComboBox3.transferFocus();
        }
        if (Tipo == "Precio De Producto Menor A") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            //jComboBox3.transferFocus();
        }
        if (Tipo == "Precio De Venta Mayor A") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            //jComboBox3.transferFocus();
        }
        if (Tipo == "Precio De Venta Menor A") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            //jComboBox3.transferFocus();
        }
    }

    void LlenarComboCateogriaProducto() {
        jComboBox2.removeAllItems();
        jComboBox2.addItem("Granel");
        jComboBox2.addItem("Material De Empaque");
        jComboBox2.addItem("Materia Prima");
        jComboBox2.addItem("Produto Terminado");
        jComboBox2.addItem("Servicio");

    }

    void LlenarComboUnidadMedida() {
        jComboBox2.removeAllItems();
        jComboBox2.addItem("Gramos");
        jComboBox2.addItem("Litros");
        jComboBox2.addItem("Kilogramos");
        jComboBox2.addItem("Unidades");

    }

    //------------------------------------------------
    void ObtenerCategoriaProducto() {

        String Aux = (String) jComboBox2.getSelectedItem();

        try {

            if (Aux == "Granel") {
                jTextField15.setText("GR");
            }
            if (Aux == "Material De Empaque") {
                jTextField15.setText("ME");
            }
            if (Aux == "Materia Prima") {
                jTextField15.setText("MP");
            }
            if (Aux == "Produto Terminado") {
                jTextField15.setText("PT");
            }
            if (Aux == "Servicio") {
                jTextField15.setText("SE");
            }

        } catch (Exception e) {
            jTextField15.setText("");
            //JT_IdPoblacion.setText("");
        }

    }

    void ObtenerUnidadMedida() {

        String Aux = (String) jComboBox2.getSelectedItem();

        try {

            if (Aux == "Gramos") {
                jTextField15.setText("GR");
            }
            if (Aux == "Litros") {
                jTextField15.setText("LI");
            }
            if (Aux == "Kilogramos") {
                jTextField15.setText("KG");
            }
            if (Aux == "Unidades") {
                jTextField15.setText("UNI");
            }

        } catch (Exception e) {
            jTextField15.setText("");
            //JT_IdPoblacion.setText("");
        }

    }

    void Consultar() {

        SentenciaSql = "select * from producto";

        String Aux;
        String Filtro = jComboBox1.getSelectedItem().toString();
        String Tipo = jComboBox3.getSelectedItem().toString();

        if (Filtro == "No") {

            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(false);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            m.Listar(SentenciaSql, jTable1);
            ConteoTabla();

        } else {
            if (Tipo == "Identificacion Producto") {

                Aux = SentenciaSql + " where id_producto like '%" + jTextField1.getText() + "%'";
                m.Listar(Aux, jTable1);

            }
            if (Tipo == "Codigo De Barras") {

                Aux = SentenciaSql + " where cod_barras_producto like '%" + jTextField1.getText() + "%'";
                m.Listar(Aux, jTable1);
            }
            if (Tipo == "Referencia De Producto") {

                Aux = SentenciaSql + " where referencia_producto like '%" + jTextField1.getText() + "%'";
                m.Listar(Aux, jTable1);
            }
            if (Tipo == "Referencia De Producto-Cliente") {

                Aux = SentenciaSql + " where referencia_producto_cliente like '%" + jTextField1.getText() + "%'";
                m.Listar(Aux, jTable1);
            }
            if (Tipo == "Descripcion De Producto") {

                Aux = SentenciaSql + " where descripcion_producto like '%" + jTextField1.getText() + "%'";
                m.Listar(Aux, jTable1);
            }
            if (Tipo == "Categoria De Producto") {

                Aux = SentenciaSql + " where categoria_producto like '%" + jTextField15.getText() + "%'";
                m.Listar(Aux, jTable1);

            }
            if (Tipo == "Unidad De Medidad") {

                Aux = SentenciaSql + " where unidad_medida like '%" + jTextField15.getText() + "%'";
                m.Listar(Aux, jTable1);

            }
            if (Tipo == "Stock Actual Mayor A") {

                Aux = SentenciaSql + " where stock_actual > '" + jTextField1.getText() + "'";
                m.Listar(Aux, jTable1);
            }
            if (Tipo == "Stock Actual Menor A") {

                Aux = SentenciaSql + " where stock_actual < '" + jTextField1.getText() + "'";
                m.Listar(Aux, jTable1);
            }
            if (Tipo == "Precio De Producto Mayor A") {

                Aux = SentenciaSql + " where precio_producto > '" + jTextField1.getText() + "'";
                m.Listar(Aux, jTable1);
            }
            if (Tipo == "Precio De Producto Menor A") {

                Aux = SentenciaSql + " where precio_producto < '" + jTextField1.getText() + "'";
                m.Listar(Aux, jTable1);
            }
            if (Tipo == "Precio De Venta Mayor A") {

                Aux = SentenciaSql + " where precio_venta_producto > '" + jTextField1.getText() + "'";
                m.Listar(Aux, jTable1);
            }
            if (Tipo == "Precio De Venta Menor A") {
                Aux = SentenciaSql + " where precio_venta_producto < '" + jTextField1.getText() + "'";
                m.Listar(Aux, jTable1);
            }
        }

    }

    void ConteoTabla() {
        int Conteo = jTable1.getRowCount();

        jLabel1.setText(String.valueOf(Conteo));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField15;
    // End of variables declaration//GEN-END:variables
}
