/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Metodos.MetodosGenerales;

/**
 *
 * @author zlaifer
 */
public class F_ConsultaClientes extends javax.swing.JInternalFrame {

    MetodosGenerales m = new MetodosGenerales();
    String TablaSql = "cliente";
    String SentenciaSql;

    public F_ConsultaClientes() {
        initComponents();
        ValidarFiltrar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(949, 490));
        setPreferredSize(new java.awt.Dimension(949, 490));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("XXX");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 390, 150, 30);

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Si" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(90, 60, 70, 30);

        jComboBox2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Seleccione Uno --", "Identificacion", "Tipo De Identificacion", "Apellidos", "Codigo Postal", "Poblacion", "Provincia", "Direccion", "Telefono", "Email", "Nickname", "Tipo De Usuario", "Fecha De Registro" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(450, 60, 210, 30);

        jComboBox3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Seleccione Uno --", "Identificacion", "Tipo De Identificacion", "Nombre Del Cliente", "Codigo Postal", "Poblacion", "Provincia", "Direccion", "Telefono", "Email" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(220, 60, 210, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(50, 100, 820, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 890, 270);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(450, 60, 210, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/consulta.png"))); // NOI18N
        jButton1.setText("CONSULTAR");
        jButton1.setToolTipText("Salir De Esta Ventana");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(650, 390, 130, 40);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("SALIR");
        jButton2.setToolTipText("Salir De Esta Ventana");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(780, 390, 120, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("FILTRAR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 60, 80, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("TOTAL USUARIOS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 390, 150, 30);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(640, 60, 140, 30);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(450, 60, 140, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("A");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(610, 60, 30, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("TIPO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 60, 80, 30);

        jTextField15.setEditable(false);
        jTextField15.setFocusable(false);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(320, 510, 150, 20);

        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLIENTES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 10, 910, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Consultar();
        ConteoTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        ValidarFiltrar();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        ValidarTipo();
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged

        String Aux = jComboBox3.getSelectedItem().toString();

        if (Aux == "Tipo De Identificacion") {
            ObtenerTipoIdentificacion();
        }
        if (Aux == "Codigo Postal") {
            ObtenerCodigoPostal();
        }
        if (Aux == "Poblacion") {
            ObtenerPoblacion();
        }
        if (Aux == "Provincia") {
            ObtenerProvincia();
        }
       
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    void ValidarFiltrar() {

        String Aux = jComboBox1.getSelectedItem().toString();
        if (Aux == "No") {
            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(false);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            Consultar();
            ConteoTabla();

        } else {

            jLabel5.setVisible(true);
            jComboBox3.setVisible(true);
//            ValidarTipo();
        }

    }

    void ValidarTipo() {

        String Tipo = jComboBox3.getSelectedItem().toString();

        if (Tipo == "Identificacion") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            jComboBox3.transferFocus();
        }
        if (Tipo == "Tipo De Identificacion") {

//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(true);
            LlenarComboTipoIdentificacion();
            jTextField1.setVisible(false);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            jComboBox3.transferFocus();

        }

        if (Tipo == "Nombre Del Cliente") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            jComboBox3.transferFocus();
        }
        if (Tipo == "Codigo Postal") {

//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(true);
            CargarComboCodPostal();
            jTextField1.setVisible(false);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            jComboBox3.transferFocus();
        }
        if (Tipo == "Poblacion") {

//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(true);
            CargarComboPoblacion();
            jTextField1.setVisible(false);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            jComboBox3.transferFocus();
        }
        if (Tipo == "Provincia") {

//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(true);
            CargarComboProvincia();
            jTextField1.setVisible(false);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            jComboBox3.transferFocus();
        }
        if (Tipo == "Direccion") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            jComboBox3.transferFocus();
        }
        if (Tipo == "Telefono") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            jComboBox3.transferFocus();
        }
        if (Tipo == "Email") {

            jTextField1.setText("");
//            jComboBox3.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel2.setVisible(false);
            jDateChooser1.setVisible(false);
            jDateChooser2.setVisible(false);
            jComboBox3.transferFocus();
        }
    }

    void LlenarComboTipoIdentificacion() {
        jComboBox2.removeAllItems();
        jComboBox2.addItem("Cedula De Ciudadania");
        jComboBox2.addItem("Cedula De Extranjeria");
        jComboBox2.addItem("NIT");

    }

    //------------------------------------------------
    void CargarComboCodPostal() {

        try {
            String Sql = "select * from codigo_postal";
            String IdSql = "id_cod_postal";
            String NombreSql = "nombre_pais";

            m.CargarLIstaComboBox(Sql, IdSql, NombreSql, "]", jComboBox2);
        } catch (Exception e) {
            System.out.println("Error cargar combopostal");
        }

    }

    void ObtenerCodigoPostal() {

        try {
            String Delimitador = "]";
            String Aux = (String) jComboBox2.getSelectedItem();
            String[] Separacion = Aux.split(Delimitador);
            jTextField15.setText(Separacion[0]);
            //JT_IdCodPostal.setText(Separacion[0]);
        } catch (Exception e) {

            System.out.println("Error obtenercodigopostal");
            jTextField15.setText("");
            //JT_IdCodPostal.setText("");
        }

    }

    void CargarComboPoblacion() {

        try {
            String Sql = "select * from poblacion";
            String IdSql = "id_poblacion";
            String NombreSql = "nombre_poblacion";

            m.CargarLIstaComboBox(Sql, IdSql, NombreSql, "]", jComboBox2);
        } catch (Exception e) {

            System.out.println("Error cargar combo poblacion");
            jComboBox3.removeAllItems();
            jTextField15.setText("");
            //JT_IdPoblacion.setText("");
        }
        //ObtenerPoblacion();
    }

    void ObtenerPoblacion() {

        String Delimitador = "]";
        String Aux = (String) jComboBox2.getSelectedItem();

        try {

            String[] Separacion = Aux.split(Delimitador);
            jTextField15.setText(Separacion[0]);
            //JT_IdPoblacion.setText(Separacion[0]);
        } catch (Exception e) {
            jTextField15.setText("");
            //JT_IdPoblacion.setText("");
        }

    }

    void CargarComboProvincia() {

        try {
            String Sql = "select * from provincia";
            String IdSql = "id_provincia";
            String NombreSql = "nombre_provincia";

            m.CargarLIstaComboBox(Sql, IdSql, NombreSql, "]", jComboBox2);
        } catch (Exception e) {
            System.out.println("Error cargar combo provincia");
            jComboBox2.removeAllItems();
            jTextField15.setText("");
            //JT_IdProvincia.setText("");

        }

        // ObtenerProvincia();
    }

    void ObtenerProvincia() {
        try {
            String Delimitador = "]";
            String Aux = (String) jComboBox2.getSelectedItem();
            String[] Separacion = Aux.split(Delimitador);
            jTextField15.setText(Separacion[0]);
            //JT_IdProvincia.setText(Separacion[0]);
        } catch (Exception e) {
            jTextField15.setText("");
            //JT_IdProvincia.setText("");
        }

    }

    void ObtenerTipoIdentificacion() {

        String Aux = (String) jComboBox2.getSelectedItem();

        try {

            if (Aux == "Cedula De Ciudadania") {
                jTextField15.setText("C.C");
            }
            if (Aux == "Cedula De Extranjeria") {
                jTextField15.setText("C.E");
            }
            if (Aux == "NIT") {
                jTextField15.setText("NIT");
            }

        } catch (Exception e) {
            jTextField15.setText("");
            //JT_IdPoblacion.setText("");
        }

    }

    void Consultar() {

        SentenciaSql = "select cliente.id_cliente,cliente.tipo_identificacion,cliente.nombre_cliente,"
                + "codigo_postal.nombre_pais,poblacion.nombre_poblacion,provincia.nombre_provincia,cliente.direccion_cliente,cliente.telefono_cliente,"
                + "cliente.email_cliente from cliente,codigo_postal,poblacion,provincia "
                + "where cliente.id_cod_postal=codigo_postal.id_cod_postal && cliente.id_poblacion_cliente=poblacion.id_poblacion && "
                + "cliente.id_provincia_cliente=provincia.id_provincia";

        String Aux;
        String Filtro = jComboBox1.getSelectedItem().toString();
        String Tipo = jComboBox3.getSelectedItem().toString();

        if (Filtro == "No") {

            m.Listar(SentenciaSql, jTable1);
        } else {
            if (Tipo == "Identificacion") {

                Aux = SentenciaSql + " && cliente.id_cliente like '%" + jTextField1.getText() + "%'";
                m.Listar(Aux, jTable1);

            }
            if (Tipo == "Tipo De Identificacion") {

                Aux = SentenciaSql + " && cliente.tipo_identificacion like '%" + jTextField15.getText() + "%'";
                m.Listar(Aux, jTable1);

            }
            if (Tipo == "Nombre Del Cliente") {

                Aux = SentenciaSql + " && cliente.nombre_cliente like '%" + jTextField1.getText() + "%'";
                m.Listar(Aux, jTable1);
            }
            if (Tipo == "Codigo Postal") {

                Aux = SentenciaSql + " && cliente.id_cod_postal like '%" + jTextField15.getText() + "%'";
                m.Listar(Aux, jTable1);

            }
            if (Tipo == "Poblacion") {

                Aux = SentenciaSql + " && cliente.id_poblacion_cliente like '%" + jTextField15.getText() + "%'";
                m.Listar(Aux, jTable1);
            }
            if (Tipo == "Provincia") {

                Aux = SentenciaSql + " && cliente.id_provincia_cliente like '%" + jTextField15.getText() + "%'";
                m.Listar(Aux, jTable1);

            }
            if (Tipo == "Direccion") {

                Aux = SentenciaSql + " && cliente.direccion_cliente like '%" + jTextField1.getText() + "%'";
                m.Listar(Aux, jTable1);
            }
            if (Tipo == "Telefono") {

                Aux = SentenciaSql + " && cliente.telefono_cliente like '%" + jTextField1.getText() + "%'";
                m.Listar(Aux, jTable1);

            }
            if (Tipo == "Email") {

                Aux = SentenciaSql + " && cliente.email_cliente like '%" + jTextField1.getText() + "%'";
                m.Listar(Aux, jTable1);

            }

        }
    }

    void ConteoTabla() {
        int Conteo = jTable1.getRowCount();

        jLabel1.setText(String.valueOf(Conteo));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField15;
    // End of variables declaration//GEN-END:variables
}
