/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Metodos.MetodosGenerales;
import Modelos.Modelo_Cliente;
import Modelos.Modelo_DetalleFactura;
import Modelos.Modelo_Factura;
import Modelos.Modelo_Producto;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;

/**
 *
 * @author zlaifer
 */
public class F_FacturaVenta_1 extends javax.swing.JInternalFrame {

    //----------------------------------herencias
    MetodosGenerales m = new MetodosGenerales();
    Modelos.Modelo_Producto mp = new Modelo_Producto();
    Modelos.Modelo_Factura mf = new Modelo_Factura();
    Modelos.Modelo_Cliente mc = new Modelo_Cliente();
    Modelos.Modelo_DetalleFactura mdf = new Modelo_DetalleFactura();
    //-----------------formatos
    DecimalFormat Df = new DecimalFormat("#,###.##");
    SimpleDateFormat Formateador_F = new SimpleDateFormat("yyyy-MM-dd");
    //------------------ variables de clase
    int Consecutivo;
    static double SubTotal = 0, CostoNeto = 0;
//    static double PrecioVentaPro = 0, CantidadPro = 0, PrecioTotalPro = 0;
    String SentenciaSql = null;
    String TablaSqlFacturaV = "facturas";
    String TablaSqlDetalleFacturaV = "detalle_factura";
    String FiltroSql = null;
    //------------banderas
    boolean BandetaBtnNuevo = false;
    boolean BandetaBtnModificar = false;
    static int BanderaAnadir = 0;

    public F_FacturaVenta_1() {
        initComponents();
        ValidarBanderaBtnNuevo();
        ValidarBanderaBtnEditar();
        ListarFacturasV();

        ListarDetalleFacturasInicial();
        DesHabilitarFactura();
        jTextField5.setText("0");
        jTextField2.setText("0");
        jTextField3.setText("0");
        jLabel8.setText("0");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_Lista_FV = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTB_JDFacturaV = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTB_Auxiliar = new javax.swing.JTable();
        JD_Lista_C = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        JTB_JDCliente = new javax.swing.JTable();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        JD_Productos = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton29 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        JD_Lista_Productos = new javax.swing.JDialog();
        jScrollPane10 = new javax.swing.JScrollPane();
        JTB_JDProducto = new javax.swing.JTable();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        JL_Consecutivo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTB_DetalleFAuxiliar = new javax.swing.JTable();
        JT_NomCliente = new javax.swing.JTextField();
        JT_IdCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        JL_Consecutivo1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        JTB_DetalleFAuxiliar1 = new javax.swing.JTable();
        JT_NomCliente1 = new javax.swing.JTextField();
        JT_IdCliente1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        JD_Lista_FV.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JD_Lista_FV.setMinimumSize(new java.awt.Dimension(530, 312));
        JD_Lista_FV.setResizable(false);
        JD_Lista_FV.getContentPane().setLayout(null);

        JTB_JDFacturaV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTB_JDFacturaV.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(JTB_JDFacturaV);

        JD_Lista_FV.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 70, 480, 150);

        jButton6.setText("ACEPTAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        JD_Lista_FV.getContentPane().add(jButton6);
        jButton6.setBounds(290, 230, 100, 40);

        jButton14.setText("SALIR");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        JD_Lista_FV.getContentPane().add(jButton14);
        jButton14.setBounds(390, 230, 110, 40);

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        JD_Lista_FV.getContentPane().add(jTextField4);
        jTextField4.setBounds(110, 40, 390, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("BUSCAR");
        JD_Lista_FV.getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 40, 90, 30);

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FACTURAS DE VENTA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        JD_Lista_FV.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 500, 280);

        JTB_Auxiliar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(JTB_Auxiliar);

        JD_Lista_FV.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(22, 350, 480, 140);

        JD_Lista_C.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JD_Lista_C.setMinimumSize(new java.awt.Dimension(530, 312));
        JD_Lista_C.setResizable(false);
        JD_Lista_C.getContentPane().setLayout(null);

        JTB_JDCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(JTB_JDCliente);

        JD_Lista_C.getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(20, 70, 480, 150);

        jButton15.setText("ACEPTAR");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        JD_Lista_C.getContentPane().add(jButton15);
        jButton15.setBounds(290, 230, 100, 40);

        jButton16.setText("SALIR");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        JD_Lista_C.getContentPane().add(jButton16);
        jButton16.setBounds(390, 230, 110, 40);

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });
        JD_Lista_C.getContentPane().add(jTextField6);
        jTextField6.setBounds(110, 40, 390, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("BUSCAR");
        JD_Lista_C.getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 40, 90, 30);

        jLabel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLIENTES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        JD_Lista_C.getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 0, 500, 280);

        JD_Productos.setMinimumSize(new java.awt.Dimension(574, 289));
        JD_Productos.setResizable(false);
        JD_Productos.getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText(" PRODUCTO");
        JD_Productos.getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 60, 130, 30);

        jTextField1.setEditable(false);
        jTextField1.setFocusable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        JD_Productos.getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 60, 110, 30);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel31.setText("DESCRIPCION");
        JD_Productos.getContentPane().add(jLabel31);
        jLabel31.setBounds(30, 90, 120, 30);

        jTextField11.setEditable(false);
        jTextField11.setFocusable(false);
        JD_Productos.getContentPane().add(jTextField11);
        jTextField11.setBounds(130, 90, 400, 30);

        jLabel32.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel32.setText("U. MEDIDA");
        JD_Productos.getContentPane().add(jLabel32);
        jLabel32.setBounds(30, 120, 90, 30);

        jTextField13.setEditable(false);
        jTextField13.setFocusable(false);
        JD_Productos.getContentPane().add(jTextField13);
        jTextField13.setBounds(130, 120, 130, 30);

        jLabel33.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel33.setText("CANTIDAD");
        JD_Productos.getContentPane().add(jLabel33);
        jLabel33.setBounds(30, 150, 90, 30);

        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField14KeyReleased(evt);
            }
        });
        JD_Productos.getContentPane().add(jTextField14);
        jTextField14.setBounds(130, 150, 130, 30);

        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/consulta.png"))); // NOI18N
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        JD_Productos.getContentPane().add(jButton29);
        jButton29.setBounds(240, 60, 30, 30);

        jLabel34.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel34.setText("TOTAL");
        JD_Productos.getContentPane().add(jLabel34);
        jLabel34.setBounds(290, 150, 100, 30);

        jTextField15.setEditable(false);
        jTextField15.setFocusable(false);
        JD_Productos.getContentPane().add(jTextField15);
        jTextField15.setBounds(390, 150, 140, 30);

        jTextField16.setEditable(false);
        jTextField16.setFocusable(false);
        JD_Productos.getContentPane().add(jTextField16);
        jTextField16.setBounds(390, 120, 140, 30);

        jLabel35.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel35.setText("PRECIO VENTA");
        JD_Productos.getContentPane().add(jLabel35);
        jLabel35.setBounds(290, 120, 100, 30);

        jButton30.setText("ACEPTAR");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        JD_Productos.getContentPane().add(jButton30);
        jButton30.setBounds(340, 200, 100, 40);

        jButton31.setText("SALIR");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        JD_Productos.getContentPane().add(jButton31);
        jButton31.setBounds(440, 200, 110, 40);

        jLabel36.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUCTOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        JD_Productos.getContentPane().add(jLabel36);
        jLabel36.setBounds(10, 20, 540, 180);

        jTextField18.setEditable(false);
        jTextField18.setFocusable(false);
        JD_Productos.getContentPane().add(jTextField18);
        jTextField18.setBounds(90, 360, 130, 40);

        JD_Lista_Productos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        JD_Lista_Productos.setMinimumSize(new java.awt.Dimension(530, 312));
        JD_Lista_Productos.setResizable(false);
        JD_Lista_Productos.getContentPane().setLayout(null);

        JTB_JDProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTB_JDProducto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        JTB_JDProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTB_JDProductoMousePressed(evt);
            }
        });
        jScrollPane10.setViewportView(JTB_JDProducto);

        JD_Lista_Productos.getContentPane().add(jScrollPane10);
        jScrollPane10.setBounds(20, 70, 480, 150);

        jButton27.setText("ACEPTAR");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        JD_Lista_Productos.getContentPane().add(jButton27);
        jButton27.setBounds(290, 230, 100, 40);

        jButton28.setText("SALIR");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        JD_Lista_Productos.getContentPane().add(jButton28);
        jButton28.setBounds(390, 230, 110, 40);

        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField10KeyReleased(evt);
            }
        });
        JD_Lista_Productos.getContentPane().add(jTextField10);
        jTextField10.setBounds(110, 40, 390, 30);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel29.setText("BUSCAR");
        JD_Lista_Productos.getContentPane().add(jLabel29);
        jLabel29.setBounds(20, 40, 90, 30);

        jLabel30.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUCTOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        JD_Lista_Productos.getContentPane().add(jLabel30);
        jLabel30.setBounds(10, 10, 500, 270);

        setTitle("FACTURA DE VENTA");
        setMinimumSize(new java.awt.Dimension(926, 511));
        setPreferredSize(new java.awt.Dimension(926, 511));
        getContentPane().setLayout(null);

        JL_Consecutivo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JL_Consecutivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_Consecutivo.setText("XXX");
        getContentPane().add(JL_Consecutivo);
        JL_Consecutivo.setBounds(520, 40, 180, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("FACTURA DE VENTA No.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 40, 180, 30);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(720, 340, 170, 30);

        JTB_DetalleFAuxiliar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTB_DetalleFAuxiliar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        JTB_DetalleFAuxiliar.setFocusable(false);
        jScrollPane1.setViewportView(JTB_DetalleFAuxiliar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 510, 630, 130);

        JT_NomCliente.setEditable(false);
        JT_NomCliente.setFocusable(false);
        getContentPane().add(JT_NomCliente);
        JT_NomCliente.setBounds(80, 80, 210, 30);

        JT_IdCliente.setEditable(false);
        JT_IdCliente.setFocusable(false);
        getContentPane().add(JT_IdCliente);
        JT_IdCliente.setBounds(80, 80, 110, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("CLIENTE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 80, 90, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("IVA %");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(600, 340, 120, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("SUB TOTAL");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(600, 310, 130, 30);

        jTextField5.setEditable(false);
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setFocusable(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(720, 310, 170, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("XXX,XX");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(720, 420, 170, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("OBSERVACIONES");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 310, 140, 40);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(760, 80, 130, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(130, 310, 440, 100);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(320, 80, 20, 30);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(590, 410, 300, 10);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("IMPRIMIR");
        jButton3.setToolTipText("Imprimir Datos De La Tabla");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(80, 0, 110, 30);

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("BUSCAR");
        jButton4.setToolTipText("Exportar Datos De  La Tabla");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(390, 0, 110, 30);

        jButton5.setText("AÑADIR");
        jButton5.setToolTipText("Adicionar Un Producto");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(20, 260, 110, 30);

        jButton9.setText("MODIFICAR");
        jButton9.setToolTipText("Modificar Productos");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(130, 260, 110, 30);

        jButton8.setText("ELIMINAR");
        jButton8.setToolTipText("Eliminar Producto");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(240, 260, 110, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.setToolTipText("Salir De Esta Ventana");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(720, 0, 110, 30);

        jButton10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton10.setText("CREAR");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(500, 0, 110, 30);

        jButton11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton11.setText("EDITAR");
        jButton11.setFocusable(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(720, 550, 110, 30);

        jButton12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton12.setText("CANCELAR");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(610, 0, 110, 30);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/consulta.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(290, 80, 30, 30);

        jButton13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton13.setText("EXPORTAR");
        getContentPane().add(jButton13);
        jButton13.setBounds(190, 0, 110, 30);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(720, 370, 170, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("DESCUENTO  %");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(600, 370, 110, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("NUMERO FACTURA");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(330, 80, 150, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable2.setFocusable(false);
        jScrollPane5.setViewportView(jTable2);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(20, 130, 870, 130);

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 120, 890, 180);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("TOTAL NETO");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(630, 420, 90, 30);

        jInternalFrame1.setTitle("FACTURA DE VENTA");
        jInternalFrame1.setMinimumSize(new java.awt.Dimension(926, 511));
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(926, 511));
        jInternalFrame1.getContentPane().setLayout(null);

        JL_Consecutivo1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JL_Consecutivo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_Consecutivo1.setText("XXX");
        jInternalFrame1.getContentPane().add(JL_Consecutivo1);
        JL_Consecutivo1.setBounds(520, 40, 180, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("FACTURA DE VENTA No.");
        jInternalFrame1.getContentPane().add(jLabel17);
        jLabel17.setBounds(350, 40, 180, 30);

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInternalFrame1.getContentPane().add(jTextField7);
        jTextField7.setBounds(720, 340, 170, 30);

        JTB_DetalleFAuxiliar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTB_DetalleFAuxiliar1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane7.setViewportView(JTB_DetalleFAuxiliar1);

        jInternalFrame1.getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(20, 510, 870, 130);
        jInternalFrame1.getContentPane().add(JT_NomCliente1);
        JT_NomCliente1.setBounds(90, 80, 220, 30);

        JT_IdCliente1.setEditable(false);
        jInternalFrame1.getContentPane().add(JT_IdCliente1);
        JT_IdCliente1.setBounds(90, 80, 110, 30);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("CLIENTE");
        jInternalFrame1.getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 80, 90, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("IVA %");
        jInternalFrame1.getContentPane().add(jLabel19);
        jLabel19.setBounds(600, 340, 120, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("SUB TOTAL");
        jInternalFrame1.getContentPane().add(jLabel20);
        jLabel20.setBounds(600, 310, 130, 30);

        jTextField8.setEditable(false);
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInternalFrame1.getContentPane().add(jTextField8);
        jTextField8.setBounds(720, 310, 170, 30);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("XXX,XX");
        jInternalFrame1.getContentPane().add(jLabel21);
        jLabel21.setBounds(720, 420, 170, 30);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("OBSERVACIONES");
        jInternalFrame1.getContentPane().add(jLabel22);
        jLabel22.setBounds(10, 310, 140, 40);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setText("TIPO-PAGO");
        jInternalFrame1.getContentPane().add(jLabel23);
        jLabel23.setBounds(360, 80, 150, 30);
        jInternalFrame1.getContentPane().add(jDateChooser3);
        jDateChooser3.setBounds(780, 80, 110, 30);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane8.setViewportView(jTextArea2);

        jInternalFrame1.getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(130, 310, 440, 110);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jInternalFrame1.getContentPane().add(jSeparator4);
        jSeparator4.setBounds(340, 80, 20, 30);
        jInternalFrame1.getContentPane().add(jSeparator5);
        jSeparator5.setBounds(590, 410, 300, 10);

        jButton17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton17.setText("IMPRIMIR");
        jButton17.setToolTipText("Imprimir Datos De La Tabla");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton17);
        jButton17.setBounds(80, 0, 110, 30);

        jButton18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton18.setText("BUSCAR");
        jButton18.setToolTipText("Exportar Datos De  La Tabla");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton18);
        jButton18.setBounds(300, 0, 110, 30);

        jButton19.setText("AÑADIR");
        jButton19.setToolTipText("Crear Nuevo Trabajador");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton19);
        jButton19.setBounds(20, 260, 110, 30);

        jButton20.setText("MODIFICAR");
        jButton20.setToolTipText("Guardar Datos");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton20);
        jButton20.setBounds(130, 260, 110, 30);

        jButton21.setText("ELIMINAR");
        jButton21.setToolTipText("Eliminar Datos");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton21);
        jButton21.setBounds(240, 260, 110, 30);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("SALIR");
        jButton2.setToolTipText("Salir De Esta Ventana");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton2);
        jButton2.setBounds(740, 0, 110, 30);

        jButton22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton22.setText("CREAR");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton22);
        jButton22.setBounds(410, 0, 110, 30);

        jButton23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton23.setText("EDITAR");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton23);
        jButton23.setBounds(520, 0, 110, 30);

        jButton24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton24.setText("CANCELAR");
        jInternalFrame1.getContentPane().add(jButton24);
        jButton24.setBounds(630, 0, 110, 30);

        jButton25.setText("jButton6");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton25);
        jButton25.setBounds(310, 80, 20, 30);

        jButton26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton26.setText("EXPORTAR");
        jInternalFrame1.getContentPane().add(jButton26);
        jButton26.setBounds(190, 0, 110, 30);

        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInternalFrame1.getContentPane().add(jTextField9);
        jTextField9.setBounds(720, 370, 170, 30);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("DESCUENTO  %");
        jInternalFrame1.getContentPane().add(jLabel24);
        jLabel24.setBounds(600, 370, 110, 30);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel25.setText("FECHA DE EXPEDICION");
        jInternalFrame1.getContentPane().add(jLabel25);
        jLabel25.setBounds(640, 80, 150, 30);
        jInternalFrame1.getContentPane().add(jTextField12);
        jTextField12.setBounds(440, 80, 150, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- SELECCIONE UNO---", "EFECTIVO" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jComboBox2);
        jComboBox2.setBounds(440, 80, 170, 30);

        jLabel26.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(255, 255, 255)));
        jInternalFrame1.getContentPane().add(jLabel26);
        jLabel26.setBounds(10, 40, 890, 80);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane9.setViewportView(jTable3);

        jInternalFrame1.getContentPane().add(jScrollPane9);
        jScrollPane9.setBounds(20, 130, 870, 130);

        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jInternalFrame1.getContentPane().add(jLabel27);
        jLabel27.setBounds(10, 120, 890, 180);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setText("TOTAL NETO");
        jInternalFrame1.getContentPane().add(jLabel28);
        jLabel28.setBounds(630, 420, 90, 30);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 0, 926, 511);

        jLabel37.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel37.setText("FECHA DE EXPEDICION");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(610, 80, 150, 30);
        getContentPane().add(jTextField17);
        jTextField17.setBounds(450, 80, 140, 30);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(600, 80, 20, 30);

        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 890, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JD_Lista_FV.setLocationRelativeTo(null);
        JD_Lista_FV.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (jButton10.getText() == "GRABAR") {
            BanderaAnadir = 0;
        }
        if (jButton11.getText() == "GRABAR") {
            BanderaAnadir = 1;
        }

        JD_Productos.setLocationRelativeTo(null);
        JD_Productos.setVisible(true);
//AdicionarFila();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        if (jButton10.getText() == "GRABAR") {
            BanderaAnadir = 2;
        }
        if (jButton11.getText() == "GRABAR") {
            BanderaAnadir = 3;
        }
        ObtenerDatosTbDetallefAProductos();
        //----------------------------------------------------------
//        JD_Productos.setLocationRelativeTo(null);
//        JD_Productos.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        if (jButton10.getText() == "GRABAR") {
            EliminarFila();
        }
        if (jButton11.getText() == "GRABAR") {
            EliminarFilaSql();
        }


    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        String AuxBtn = jButton10.getText();
        if (AuxBtn.equals("NUEVO")) {
            BandetaBtnNuevo = true;
            BandetaBtnModificar = false;
            //Habilitar();

        } else {
            BandetaBtnNuevo = false;
            //DesHabilitar();
        }

//        Limpiar();
//        Habilitar();
        ComprobarBtn();
        ValidarBanderaBtnNuevo();
        ValidarBanderaBtnEditar();

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        BandetaBtnNuevo = false;
        BandetaBtnModificar = false;

        ValidarBanderaBtnNuevo();
        ValidarBanderaBtnEditar();
        //-------------------
        jTextField5.setText("0");
        jTextField2.setText("0");
        jTextField3.setText("0");
        jLabel8.setText("0");
        ObtenerDatosListaClientes();
        jTextField4.setText("");
        ListarDetalleFacturasV();
        ListarDetalleFacturasV_Aux();
        SumaTabla();
        this.JD_Lista_FV.dispose();
        DesHabilitarFactura();
        jButton11.setEnabled(true);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        jTextField4.setText("");
        this.JD_Lista_FV.dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        ListarFacturasV();
        ListarFacturasV_Aux();
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String AuxBtn = jButton11.getText();
        if (AuxBtn.equals("EDITAR")) {
            BandetaBtnModificar = true;
            //Habilitar();

        } else {
            BandetaBtnModificar = false;
            //DesHabilitar();
        }

//        Limpiar();
//        Habilitar();
        ComprobarBtnEditar();
        ValidarBanderaBtnEditar();

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        ObtenerDatosListaC();
        this.JD_Lista_C.dispose();
        jTextField6.setText("");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        jTextField6.setText("");
        this.JD_Lista_C.dispose();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        ListarClientes();
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ListarClientes();
        JD_Lista_C.setLocationRelativeTo(null);
        JD_Lista_C.setVisible(true);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        //ObtenerDatosListaProductos();
        ValidarProductoTablaDetalleF();
        //--------------------------------------------------------------------------------

    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        this.JD_Lista_Productos.dispose();
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jTextField10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyReleased
        ListarProductos();
    }//GEN-LAST:event_jTextField10KeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        ValidarStockProducto();
        SumaTabla();
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        this.JD_Productos.dispose();
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        ListarProductos();
        JD_Lista_Productos.setLocationRelativeTo(null);
        JD_Lista_Productos.setVisible(true);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void JTB_JDProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTB_JDProductoMousePressed

    }//GEN-LAST:event_JTB_JDProductoMousePressed

    private void jTextField14KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyReleased
        CalcularPrecioTotalPro();
    }//GEN-LAST:event_jTextField14KeyReleased

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

        BandetaBtnNuevo = false;
        BandetaBtnModificar = false;
        ValidarBanderaBtnNuevo();
        ValidarBanderaBtnEditar();
        LimpiarFactura();
        DesHabilitarFactura();

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        SumaTabla();
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        SumaTabla();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased
//-----------------------

    //---------- Metodos Factura
    void LimpiarFactura() {

        ListarDetalleFacturasInicial();
        m.LimpiarJText(JT_IdCliente);
        m.LimpiarJText(JT_NomCliente);
        m.LimpiarJText(jTextField17);
        m.LimpiarJDate(jDateChooser2);
        JL_Consecutivo.setText("XXX");

        jTextField5.setText("0");
        jTextField2.setText("0");
        jTextField3.setText("0");
        jLabel8.setText("0");
        jTextArea1.setText("");

    }

    void HabilitarFactura() {

        m.HabilitarJBtn(jButton7);
        m.DesHabilitarJBtn(jButton11);
        m.HabilitarJBtn(jButton12);

        m.HabilitarJBtn(jButton5);
        m.HabilitarJBtn(jButton9);
        m.HabilitarJBtn(jButton8);

        m.HabilitarJText(jTextField17);
        m.HabilitarJText(jTextField2);
        m.HabilitarJText(jTextField3);
        jTextArea1.setEnabled(true);
        m.HabilitarJDate(jDateChooser2);
    }

    void HabilitarFacturaTabla() {

        m.HabilitarJBtn(jButton7);
        m.HabilitarJBtn(jButton11);
        m.HabilitarJBtn(jButton12);

        m.HabilitarJBtn(jButton5);
        m.HabilitarJBtn(jButton9);
        m.HabilitarJBtn(jButton8);

        m.HabilitarJText(jTextField17);
        m.HabilitarJText(jTextField2);
        m.HabilitarJText(jTextField3);
        jTextArea1.setEnabled(true);
        m.HabilitarJDate(jDateChooser2);
    }

    void DesHabilitarFactura() {

        m.DesHabilitarJBtn(jButton7);
        m.DesHabilitarJBtn(jButton11);
        m.DesHabilitarJBtn(jButton12);

        m.DesHabilitarJBtn(jButton5);
        m.DesHabilitarJBtn(jButton9);
        m.DesHabilitarJBtn(jButton8);

        m.DesHabilitarJText(jTextField17);
        m.DesHabilitarJText(jTextField2);
        m.DesHabilitarJText(jTextField3);
        jTextArea1.setEnabled(false);
        m.DesHabilitarJDate(jDateChooser2);
    }

    void CargarConsecutivo() {

//        m.cargar_consecutivo("id_factura", "facturas", JL_Consecutivo);
//        m.ObtenerConsecutivoModificado("facturas", JL_Consecutivo);
    }

    void ValidarBanderaBtnNuevo() {

        if (BandetaBtnNuevo == false) {
            jButton10.setText("NUEVO");
        } else {
            jButton10.setText("GRABAR");
        }

    }

    void ValidarBanderaBtnEditar() {

        if (BandetaBtnModificar == false) {
            jButton11.setText("EDITAR");
            // BanderaAnadir = 0;
        } else {
            jButton11.setText("GRABAR");
            //BanderaAnadir = 1;

        }

    }
    //-------------------------------------------

    void ComprobarBtn() {

        String Aux = jButton10.getText();

        if (Aux.equals("NUEVO")) {

            LimpiarFactura();
            CargarConsecutivo();
            HabilitarFactura();
            JT_NomCliente.transferFocus();

        } else {

            GrabarFactura();
            LimpiarFactura();
            ListarFacturasV();
            DesHabilitarFactura();
        }
    }

    void ComprobarBtnEditar() {

        String Aux = jButton11.getText();

        if (Aux.equals("EDITAR")) {

//            LimpiarFactura();
//            CargarConsecutivo();
//            HabilitarFactura();
//            JT_NomCliente.transferFocus();
            HabilitarFacturaTabla();

        } else {

            ModificarFactura();
            //------------------------------
            LimpiarFactura();
            ListarFacturasV();
            DesHabilitarFactura();
        }
    }

    void ListarDetalleFacturasInicial() {
        // Consecutivo = Integer.parseInt(JL_Consecutivo.getText());
        String Sql = "select detalle_factura.id_producto,"
                + "producto.descripcion_producto,producto.unidad_medida,detalle_factura.cantidad_producto,"
                + "producto.precio_venta_producto,detalle_factura.total from detalle_factura,producto,facturas "
                + "where detalle_factura.id_factura=facturas.id_factura && "
                + "detalle_factura.id_producto=producto.id_producto && detalle_factura.id_factura=1000000000000";
        m.Listar(Sql, jTable2);

    }

    void ListarFacturasV() {
        String FiltroSql = jTextField4.getText();
        String Sql = "select facturas.id_factura, cliente.nombre_cliente, facturas.total_factura, "
                + "facturas.fecha_factura from facturas,cliente where facturas.id_cliente=cliente.id_cliente "
                + "&& concat(facturas.id_factura, cliente.nombre_cliente) like '%" + FiltroSql + "%'";
        m.Listar(Sql, JTB_JDFacturaV);
        ListarFacturasV_Aux();

    }

    void ListarFacturasV_Aux() {
        String FiltroSql = jTextField4.getText();
        String Sql = "select facturas.id_factura, facturas.num_factura, facturas.forma_pago, facturas.cuota_iva_factura,"
                + "facturas.descuento_factura, facturas.id_cliente, cliente.nombre_cliente, "
                + "facturas.fecha_factura,facturas.observaciones from facturas,cliente where facturas.id_cliente=cliente.id_cliente "
                + "&& concat(facturas.id_factura, cliente.nombre_cliente) like '%" + FiltroSql + "%'";
        m.Listar(Sql, JTB_Auxiliar);

    }

    void ObtenerDatosListaClientes() {

        int fila = JTB_JDFacturaV.getSelectedRow();

        String Fecha = JTB_Auxiliar.getValueAt(fila, 7).toString();
        Date fecha = null;
        try {

            fecha = Formateador_F.parse(Fecha);
            jDateChooser2.setDate(fecha);

        } catch (Exception e) {
            System.out.println("error al convertir la fecha");
        }

        if (fila >= 0) {

            JL_Consecutivo.setText(JTB_Auxiliar.getValueAt(fila, 0).toString());
            jTextField17.setText(JTB_Auxiliar.getValueAt(fila, 1).toString());
            //jTextField11.setText(JTB_Auxiliar.getValueAt(fila, 2).toString());
            jTextField2.setText(JTB_Auxiliar.getValueAt(fila, 3).toString());
            jTextField3.setText(JTB_Auxiliar.getValueAt(fila, 4).toString());
            JT_IdCliente.setText(JTB_Auxiliar.getValueAt(fila, 5).toString());
            JT_NomCliente.setText(JTB_Auxiliar.getValueAt(fila, 6).toString());
            jTextArea1.setText(JTB_Auxiliar.getValueAt(fila, 8).toString());

        } else {

            JOptionPane.showMessageDialog(null, "no selecciono fila");
        }

    }

    void CalcularCostoNeto(double Iva, double Descuento) {

        CostoNeto = (SubTotal + Iva) - Descuento;

        jLabel8.setText(Df.format(CostoNeto));

    }

    public double CalcularIva() {

        double TotalIva = 0;
        int Iva = 0;

        Iva = Integer.valueOf(jTextField2.getText().toString());
        if (Iva == 0) {
            return 0;
        } else {

            TotalIva = (SubTotal * Iva) / 100;

            return TotalIva;

        }

    }

    public double CalcularDescuento() {

        double TotalDescuento = 0;
        int Descuento = 0;

        Descuento = Integer.valueOf(jTextField3.getText().toString());
        if (Descuento == 0) {
            return 0;
        } else {

            TotalDescuento = (SubTotal * Descuento) / 100;

            return TotalDescuento;

        }

    }

    void GrabarFactura() {

        mf.setIdFactura(Integer.parseInt(JL_Consecutivo.getText()));
        mf.setNumeroFactura(jTextField17.getText());
        mf.setFormaPago("EFECTIVO");
        String FechaFactura = m.ConvertirFechaString(jDateChooser2);
        mf.setSubTotalFactura(SubTotal);
        mf.setCuotaIva(Integer.valueOf(jTextField2.getText()));
        mf.setDescuentoFactura(Integer.valueOf(jTextField3.getText()));
        mf.setTotalFactura(CostoNeto);
        mc.setIdCliente(JT_IdCliente.getText());
        mf.setObservaciones(jTextArea1.getText());

        SentenciaSql = "'" + mf.getIdFactura() + "' , '" + mf.getNumeroFactura() + "' , '" + mf.getFormaPago() + "' , '" + FechaFactura
                + "' , '" + mf.getSubTotalFactura() + "' , '" + mf.getCuotaIva() + "' , '" + mf.getDescuentoFactura() + "' , '" + mf.getTotalFactura()
                + "' , '" + mc.getIdCliente() + "' , '" + mf.getObservaciones() + "'";
        m.Grabar(TablaSqlFacturaV, SentenciaSql);

        GrabarDetalleF();

//        Limpiar();
//        Listar();
    }

    //-------------- Metodos Detalle Factura
    void GrabarDetalleF() {

        int Fila = jTable2.getRowCount();
        for (int i = 0; i < Fila; i++) {
            mf.setIdFactura(Integer.parseInt(JL_Consecutivo.getText()));
            mp.setIdProducto(jTable2.getValueAt(i, 0).toString());
            mdf.setCantidadProducto(Double.parseDouble(jTable2.getValueAt(i, 3).toString()));
            mdf.setPrecioTotalProducto(Double.parseDouble(jTable2.getValueAt(i, 5).toString()));

            SentenciaSql = "NULL,'" + mf.getIdFactura() + "' , '" + mp.getIdProducto() + "' , '" + mdf.getCantidadProducto()
                    + "' , '" + mdf.getPrecioTotalProducto() + "'";
            m.GrabarHidden(TablaSqlDetalleFacturaV, SentenciaSql);
        }

//        Limpiar();
//        Listar();
    }

    void ModificarFactura() {

        mf.setIdFactura(Integer.parseInt(JL_Consecutivo.getText()));
        mf.setNumeroFactura(jTextField17.getText());
        mf.setFormaPago("EFECTIVO");
        String FechaFactura = m.ConvertirFechaString(jDateChooser2);
        mf.setSubTotalFactura(SubTotal);
        mf.setCuotaIva(Integer.valueOf(jTextField2.getText()));
        mf.setDescuentoFactura(Integer.valueOf(jTextField3.getText()));
        mf.setTotalFactura(CostoNeto);
        mc.setIdCliente(JT_IdCliente.getText());
        mf.setObservaciones(jTextArea1.getText());

        SentenciaSql = "num_factura='" + mf.getNumeroFactura() + "',forma_pago='" + mf.getFormaPago() + "',fecha_factura='" + FechaFactura
                + "',subtotal_factura='" + mf.getSubTotalFactura() + "',cuota_iva_factura='" + mf.getCuotaIva() + "',descuento_factura='"
                + mf.getDescuentoFactura() + "',total_factura='" + mf.getTotalFactura()
                + "',id_cliente='" + mc.getIdCliente() + "',observaciones='" + mf.getObservaciones() + "' where id_factura='" + mf.getIdFactura() + "'";
        m.Modificar(TablaSqlFacturaV, SentenciaSql);

//        GrabarDetalleF();
//        Limpiar();
//        Listar();
    }
    //-----------------------------------------------------   

    void ListarDetalleFacturasV() {
        Consecutivo = Integer.parseInt(JL_Consecutivo.getText());
        String Sql = "select detalle_factura.id_producto,"
                + "producto.descripcion_producto,producto.unidad_medida,detalle_factura.cantidad_producto,"
                + "producto.precio_venta_producto,detalle_factura.total from detalle_factura,producto,facturas "
                + "where detalle_factura.id_factura=facturas.id_factura && "
                + "detalle_factura.id_producto=producto.id_producto && detalle_factura.id_factura=" + Consecutivo;
        m.Listar(Sql, jTable2);
        ListarDetalleFacturasV_Aux();

    }

    void ListarDetalleFacturasV_Aux() {
        Consecutivo = Integer.parseInt(JL_Consecutivo.getText());
        String Sql = "select detalle_factura.id_detalle_factura,detalle_factura.id_producto,"
                + "producto.descripcion_producto,producto.unidad_medida,detalle_factura.cantidad_producto,"
                + "producto.precio_venta_producto from detalle_factura,producto,facturas "
                + "where detalle_factura.id_factura=facturas.id_factura && "
                + "detalle_factura.id_producto=producto.id_producto && detalle_factura.id_factura=" + Consecutivo;
        m.ListarDetalle(Sql, JTB_DetalleFAuxiliar);

    }

    void SumaTabla() {

        SubTotal = 0;
        double ValorTabla = 0;
        try {
            int Filas = jTable2.getRowCount();

            if (Filas > 0) {
                for (int i = 0; i < Filas; i++) {
                    ValorTabla = Double.valueOf(jTable2.getValueAt(i, 5).toString());

                    SubTotal = SubTotal + ValorTabla;
                    System.out.println("Sumando " + SubTotal + " + " + ValorTabla);
//        System.out.println("sale " + suma);
                    jTextField5.setText(Df.format(SubTotal));

                    CalcularCostoNeto(CalcularIva(), CalcularDescuento());
                }
            } else {
                jTextField5.setText("0");
                jTextField2.setText("0");
                jTextField3.setText("0");
                jLabel8.setText("0");
            }

        } catch (Exception e) {
            System.out.println("Error Metodo SumaTabla");
        }

    }

    void CalcularPrecioTotalPro() {

        double Aux;

        try {

            mdf.setCantidadProducto(Double.valueOf(jTextField14.getText()));
//            CantidadPro = Double.valueOf(jTextField14.getText());
            //PrecioVentaPro = Double.valueOf(jTextField16.getText());

//            PrecioTotalPro = CantidadPro * PrecioVentaPro;
            Aux = mdf.getCantidadProducto() * mp.getPrecioProductoVenta();
            mdf.setPrecioTotalProducto(Aux);
            jTextField15.setText(Df.format(Aux));
            System.out.println("precio total producto: " + mdf.getPrecioTotalProducto());
        } catch (Exception e) {
            System.out.println("Error Calcular Precio Total");
        }

    }

    void AdicionarFila() {

        // LimpiarJD_Productos();
        try {

            //double PrecioTotalRedondeado = Math.round(PrecioTotalPro*100)/10000;
            mp.setIdProducto(jTextField1.getText());
            mp.setDescripcionCliente(jTextField11.getText());
            //mp.setPrecioProductoVenta(jTextField16.getText());
            mp.setUnidadMedidad(jTextField13.getText());
            mdf.setCantidadProducto(Double.valueOf(jTextField14.getText()));

            Object object[] = {mp.getIdProducto(), mp.getDescripcionCliente(), mp.getUnidadMedidad(), mdf.getCantidadProducto(), mp.getPrecioProductoVenta(), mdf.getPrecioTotalProducto()

            };

            m.AdicionarFila(jTable2, object);

            LimpiarJD_Productos();
            SumaTabla();
        } catch (Exception e) {
            System.out.println("Error en Adicionar Fila");
        }

    }

    void ModificarFila() {

//        LimpiarJD_Productos();
        int Fila = jTable2.getSelectedRow();
        try {
            mp.setIdProducto(jTextField1.getText());
            mp.setDescripcionCliente(jTextField11.getText());
            //mp.setPrecioProductoVenta(jTextField16.getText());
            mp.setUnidadMedidad(jTextField13.getText());
            mdf.setCantidadProducto(Double.valueOf(jTextField14.getText()));

            Object object[] = {mp.getIdProducto(), mp.getDescripcionCliente(), mp.getUnidadMedidad(), mdf.getCantidadProducto(), mp.getPrecioProductoVenta(), mdf.getPrecioTotalProducto()

            };
            m.ModificarFila(jTable2, Fila, 0, mp.getIdProducto());
            m.ModificarFila(jTable2, Fila, 1, mp.getDescripcionCliente());
            m.ModificarFila(jTable2, Fila, 2, mp.getUnidadMedidad());
            m.ModificarFila(jTable2, Fila, 3, mdf.getCantidadProducto());
            m.ModificarFila(jTable2, Fila, 4, mp.getPrecioProductoVenta());
            m.ModificarFila(jTable2, Fila, 5, mdf.getPrecioTotalProducto());

            SumaTabla();
            LimpiarJD_Productos();
        } catch (Exception e) {
            System.out.println("Error En Metodo Eliminar Fila");
        }
    }

    void EliminarFila() {

        int Fila = jTable2.getSelectedRow();
        try {
            m.EliminarFila(jTable2, Fila);
            SumaTabla();
        } catch (Exception e) {
            System.out.println("Error En Metodo Eliminar Fila");
        }
    }

    void AdicionarFilaSql() {

//        LimpiarJD_Productos();
        try {

            mf.setIdFactura(Integer.parseInt(JL_Consecutivo.getText()));
            mp.setIdProducto(jTextField1.getText());
            mdf.setCantidadProducto(Double.parseDouble(jTextField14.getText()));
            //mdf.setPrecioTotalProducto(Double.parseDouble(jTextField15.getText()));
            SentenciaSql = "NULL,'" + mf.getIdFactura() + "' , '" + mp.getIdProducto() + "' , '" + mdf.getCantidadProducto()
                    + "' , '" + mdf.getPrecioTotalProducto() + "'";

            m.GrabarHidden(TablaSqlDetalleFacturaV, SentenciaSql);
            LimpiarJD_Productos();
            ListarDetalleFacturasV();
            SumaTabla();
//            ListarDetalleFacturasV_Aux();
        } catch (Exception e) {
            System.out.println("Error en Adicionar Fila Detalle Factura:\n " + e);

//            m.GrabarHidden(TablaSqlDetalleFacturaV, SentenciaSql);
//            LimpiarJD_Productos();
//            ListarDetalleFacturasV();
        }

    }

    void ModificarFilaSql() {

//        LimpiarJD_Productos();
        int Fila = jTable2.getSelectedRow();
        try {
            mdf.setIdDetalleFactura(Integer.parseInt(JTB_DetalleFAuxiliar.getValueAt(Fila, 0).toString()));
            mp.setIdProducto(jTextField1.getText());
            //mp.setDescripcionCliente(jTextField11.getText());
            //mp.setPrecioProductoVenta(jTextField16.getText());
            //mp.setUnidadMedidad(jTextField13.getText());
            mdf.setCantidadProducto(Double.valueOf(jTextField14.getText()));

            SentenciaSql = "id_producto='" + mp.getIdProducto() + "',cantidad_producto='" + mdf.getCantidadProducto()
                    + "',total='" + mdf.getPrecioTotalProducto() + "' where id_detalle_factura=" + mdf.getIdDetalleFactura();

            m.ModificarHidden(TablaSqlDetalleFacturaV, SentenciaSql);
            LimpiarJD_Productos();
            ListarDetalleFacturasV();
            SumaTabla();

        } catch (Exception e) {
            System.out.println("Error En Metodo Eliminar Fila");
        }
    }

    void EliminarFilaSql() {

        int Fila = jTable2.getSelectedRow();
        try {

            mdf.setIdDetalleFactura(Integer.parseInt(JTB_DetalleFAuxiliar.getValueAt(Fila, 0).toString()));

            SentenciaSql = "id_detalle_factura=" + mdf.getIdDetalleFactura();

            m.Eliminar(TablaSqlDetalleFacturaV, SentenciaSql);
            ListarDetalleFacturasV();
            SumaTabla();
        } catch (Exception e) {
            System.out.println("Error En Metodo Eliminar Fila");
        }
    }

    //-------------- Metodos Clientes
    void ListarClientes() {
        String FiltroSql = jTextField6.getText();
        String Sql = "select cliente.id_cliente, cliente.nombre_cliente from cliente where"
                + " concat(cliente.id_cliente, cliente.nombre_cliente) like '%" + FiltroSql + "%'";
        m.Listar(Sql, JTB_JDCliente);

    }

    void ObtenerDatosListaC() {

        int fila = JTB_JDCliente.getSelectedRow();

        if (fila >= 0) {

            JT_IdCliente.setText(JTB_JDCliente.getValueAt(fila, 0).toString());
            JT_NomCliente.setText(JTB_JDCliente.getValueAt(fila, 1).toString());

        } else {

            JOptionPane.showMessageDialog(null, "no selecciono fila");
        }

    }

    //--------------- Metodos Productos
    void ListarProductos() {
        String FiltroSql = jTextField10.getText();
        String Sql = "select id_producto, descripcion_producto,stock_actual,precio_venta_producto,unidad_medida from producto where"
                + " concat(id_producto,descripcion_producto) like '%" + FiltroSql + "%'";
        m.Listar(Sql, JTB_JDProducto);

    }

    void ObtenerDatosListaProductos() {

        int fila = JTB_JDProducto.getSelectedRow();

        if (fila >= 0) {

            // aqui toma el valor de precioventa
            try {
                //PrecioVentaPro = Double.valueOf(JTB_JDProducto.getValueAt(fila, 3).toString()); jTextField18

                mp.setIdProducto((JTB_JDProducto.getValueAt(fila, 0).toString()));
                mp.setDescripcionCliente((JTB_JDProducto.getValueAt(fila, 1).toString()));
                jTextField18.setText(JTB_JDProducto.getValueAt(fila, 2).toString());
                mp.setPrecioProductoVenta(Double.valueOf(JTB_JDProducto.getValueAt(fila, 3).toString()));
                mp.setUnidadMedidad((JTB_JDProducto.getValueAt(fila, 4).toString()));

                jTextField1.setText(mp.getIdProducto());
                jTextField11.setText(mp.getDescripcionCliente());
//                jTextField16.setText(Df.format(PrecioVentaPro));
                jTextField16.setText(Df.format(mp.getPrecioProductoVenta()));
                jTextField13.setText(mp.getUnidadMedidad());
                //(CantidadPro = Double.valueOf(jTextField14.getText());

                this.JD_Lista_Productos.dispose();
            } catch (Exception e) {
                System.out.println("Error Obtener Datos Lista Productos");
            }

        } else {

            JOptionPane.showMessageDialog(null, "no selecciono fila");
        }
        CalcularPrecioTotalPro();
    }

    void ObtenerDatosTbDetallefAProductos() {

        int fila = jTable2.getSelectedRow();

        if (fila >= 0) {
            JD_Productos.setLocationRelativeTo(null);
            JD_Productos.setVisible(true);

            // aqui toma el valor de precioventa
            try {
                //PrecioVentaPro = Double.valueOf(JTB_JDProducto.getValueAt(fila, 3).toString());

                mp.setIdProducto((jTable2.getValueAt(fila, 0).toString()));
                mp.setDescripcionCliente((jTable2.getValueAt(fila, 1).toString()));
                mp.setUnidadMedidad((jTable2.getValueAt(fila, 2).toString()));
                mdf.setCantidadProducto(Double.valueOf(jTable2.getValueAt(fila, 3).toString()));
                mp.setPrecioProductoVenta(Double.valueOf(jTable2.getValueAt(fila, 4).toString()));
                mdf.setPrecioTotalProducto(Double.valueOf(jTable2.getValueAt(fila, 5).toString()));

                jTextField1.setText(mp.getIdProducto());
                jTextField11.setText(mp.getDescripcionCliente());
                jTextField13.setText(mp.getUnidadMedidad());
                jTextField16.setText(Df.format(mp.getPrecioProductoVenta()));
                jTextField15.setText(Df.format(mdf.getPrecioTotalProducto()));

                //(CantidadPro = Double.valueOf(jTextField14.getText());
            } catch (Exception e) {
                System.out.println("Error Obtener Datos Lista Productos");
            }

        } else {

            JOptionPane.showMessageDialog(null, "no selecciono fila");
        }
        CalcularPrecioTotalPro();
    }

    void ValidarProductoTablaDetalleF() {

        int BanderaProducto = 0;
        int FilaListaProductos = JTB_JDProducto.getSelectedRow();
        int Fila = jTable2.getRowCount();
        try {
            String Producto = JTB_JDProducto.getValueAt(FilaListaProductos, 0).toString();

            if (Fila == 0) {
                ObtenerDatosListaProductos();
                System.out.println("la tabla esta vacia");
            } else {
                for (int j = 0; j < Fila; j++) {
                    String Aux = jTable2.getValueAt(j, 0).toString();

                    if (!Producto.equals(Aux)) {
                        System.out.println("los valores: " + Producto + " y " + Aux + "  son distintos");
                        BanderaProducto = BanderaProducto + 0;
//                        ObtenerDatosListaProductos();
                        //-----------------------------------------------------------------
                    }
                    if (Producto.equals(Aux)) {

                        System.out.println("los valores: " + Producto + " y " + Aux + "  son iguales");
                        BanderaProducto = BanderaProducto + 1;
//                    JOptionPane.showMessageDialog(null, "Solo Puede Haber Un Producto De Cada Uno","Error Producto",JOptionPane.ERROR_MESSAGE);
                        break;

                    }
                }
                if (BanderaProducto == 0) {
                    ObtenerDatosListaProductos();
                }
                if (BanderaProducto == 1) {
                    JOptionPane.showMessageDialog(null, "Solo Puede Haber Un Producto De Cada Uno", "Error Producto", JOptionPane.ERROR_MESSAGE);
                    BanderaProducto = BanderaProducto - 1;
                }

            }
        } catch (Exception e) {
            System.out.println("error en metod validarproducto tabla detalles");
        }

    }

    void ValidarStockProducto() {

        double StockActual = Double.parseDouble(jTextField18.getText());
        double Cantidad = Double.parseDouble(jTextField14.getText());
        if (Cantidad > StockActual) {

            JOptionPane.showMessageDialog(null, "La Cantidad No Puede Ser Mayor Al Stock Actual", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (BanderaAnadir == 0) {

                AdicionarFila();
            }
            if (BanderaAnadir == 1) {

                AdicionarFilaSql();
            }
            if (BanderaAnadir == 2) {

//            AdicionarFilaDetalleF();
                ModificarFila();
            }
            if (BanderaAnadir == 3) {

                ModificarFilaSql();
            }

            this.JD_Productos.dispose();
        }
    }

    void LimpiarJD_Productos() {

        m.LimpiarJText(jTextField1);
        m.LimpiarJText(jTextField11);
        m.LimpiarJText(jTextField16);
        m.LimpiarJText(jTextField13);
        m.LimpiarJText(jTextField15);
        m.LimpiarJText(jTextField14);

    }
        //----------------------------------    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDialog JD_Lista_C;
    public static javax.swing.JDialog JD_Lista_FV;
    public static javax.swing.JDialog JD_Lista_Productos;
    private javax.swing.JDialog JD_Productos;
    public static javax.swing.JLabel JL_Consecutivo;
    public static javax.swing.JLabel JL_Consecutivo1;
    private javax.swing.JTable JTB_Auxiliar;
    private javax.swing.JTable JTB_DetalleFAuxiliar;
    private javax.swing.JTable JTB_DetalleFAuxiliar1;
    private javax.swing.JTable JTB_JDCliente;
    private javax.swing.JTable JTB_JDFacturaV;
    private javax.swing.JTable JTB_JDProducto;
    private javax.swing.JTextField JT_IdCliente;
    private javax.swing.JTextField JT_IdCliente1;
    public static javax.swing.JTextField JT_NomCliente;
    public static javax.swing.JTextField JT_NomCliente1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox2;
    public static com.toedter.calendar.JDateChooser jDateChooser2;
    public static com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    public static javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
