/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Frames;

import Metodos.Conexion;
import Metodos.MetodosGenerales;
import Metodos.FechaActual;
import com.mysql.jdbc.Statement;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author zlaifer
 */
public class F_Loggin extends javax.swing.JFrame {

    MetodosGenerales m=new MetodosGenerales();
    Metodos.FechaActual fa=new FechaActual();
    Conexion cc = new Conexion();
    Connection con = cc.Conexion();
    java.sql.Statement sent;

    public static String CapturarTipoUsuario;
    public static String CapturarNombres;
    public static String CapturarApellidos;
    public static String CapturarNickname;
    public static String CapturarConstrasena;
    public F_Loggin() {
        initComponents();
        this.setLocationRelativeTo(null);
        JL_Fecha.setText(fa.fecha());
        CargarComboUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JT_User = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JT_Pass = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        JL_Error = new javax.swing.JLabel();
        JL_Error1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JL_Fecha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(484, 293));
        setPreferredSize(new java.awt.Dimension(484, 293));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("USUARIO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 50, 121, 29);

        JT_User.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        JT_User.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(JT_User);
        JT_User.setBounds(280, 50, 150, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("CONTRASEÑA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 90, 121, 29);

        JT_Pass.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        JT_Pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        JT_Pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JT_PassKeyReleased(evt);
            }
        });
        getContentPane().add(JT_Pass);
        JT_Pass.setBounds(280, 90, 170, 30);

        jComboBox1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jComboBox1.setFocusable(false);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(280, 50, 170, 30);

        jButton7.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton7.setText("Ingresar");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(230, 150, 110, 40);

        jButton6.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton6.setText("Cancelar");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(340, 150, 110, 40);

        JL_Error.setFont(new java.awt.Font("Cambria", 0, 10)); // NOI18N
        JL_Error.setForeground(new java.awt.Color(255, 255, 255));
        JL_Error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(JL_Error);
        JL_Error.setBounds(280, 120, 170, 30);

        JL_Error1.setFont(new java.awt.Font("Cambria", 0, 10)); // NOI18N
        JL_Error1.setForeground(new java.awt.Color(255, 0, 0));
        JL_Error1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(JL_Error1);
        JL_Error1.setBounds(270, 80, 190, 30);

        jButton5.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton5.setText("Salir");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(350, 210, 110, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tesocartera-logo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 150, 150);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("FECHA:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 210, 80, 30);

        JL_Fecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JL_Fecha.setText("Fecha: ");
        getContentPane().add(JL_Fecha);
        JL_Fecha.setBounds(90, 210, 120, 30);

        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TESOCARTERA SYSTEM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 0, 450, 200);

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Version 1.0");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 240, 60, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JT_PassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JT_PassKeyReleased

        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
          validar();  
        
        }
    }//GEN-LAST:event_JT_PassKeyReleased

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        ObtenerCombo();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        validar();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Loggin().setVisible(true);
            }
        });
    }
//--------------------
    void CargarComboUsuario() {

        try {
            String Sql = "select * from usuario";
            String Nickname = "nickname";
           

            m.CargarComboBox(Sql,"nickname", jComboBox1);
        } catch (Exception e) {
            System.out.println("Error cargar combo usuario");
           
        }
    }
    void ObtenerCombo(){
        m.JComboBox(jComboBox1, JT_User);
    }
     public void acceder(String usuario, String pass) {

        String sql = "select * from usuario where nickname='" + usuario + "'&& contrasena='" + pass + "'";

        try {

            Statement st = (Statement) con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                CapturarTipoUsuario = rs.getString("tipo_usuario");
                CapturarApellidos = rs.getString("apellidos_usuario");
                CapturarNombres = rs.getString("nombres_usuario");
                CapturarNickname=rs.getString("nickname");
                CapturarConstrasena = rs.getString("contrasena");

            }
            if (usuario.equals(CapturarNickname) && pass.equals(CapturarConstrasena)) {
                F_Escritorio JF_P = new F_Escritorio();
                JF_P.setVisible(true);

                dispose();
            } 
            else {
                limpiar();
                JL_Error.setText("¡¡¡Usuario O Contraseña Incorrecta!!!");

            }
        } catch (Exception e) {
            System.out.println("Error Al Ejecutar El Metodo Acceder");
        }
    }
//    }

    void limpiar() {
        JT_User.setText("");
        JT_Pass.setText("");

    }

    void validar() {

        if (JT_User.getText().length() == 0 || JT_Pass.getText().length() == 0) {

            JOptionPane.showMessageDialog(this, "Ningun Campo Puede Estar Vacio", "Campos Vacios", JOptionPane.ERROR_MESSAGE);

        } else {
            acceder(JT_User.getText(), JT_Pass.getText());

        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_Error;
    private javax.swing.JLabel JL_Error1;
    private javax.swing.JLabel JL_Fecha;
    private javax.swing.JPasswordField JT_Pass;
    private javax.swing.JTextField JT_User;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
