/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Metodos.Conexion;
import Metodos.MetodosGenerales;
import Modelos.Modelo_CodigoPostal;
import Modelos.Modelo_Poblacion;
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author zlaifer
 */
public class F_Poblacion extends javax.swing.JInternalFrame {

    Metodos.MetodosGenerales m = new MetodosGenerales();
    Modelos.Modelo_CodigoPostal mcp = new Modelo_CodigoPostal();
    Modelos.Modelo_Poblacion mp = new Modelo_Poblacion();
    boolean BanderaNuevo = false;
    String FiltroSql, SentenciaSql;
    String TablaSql = "poblacion";
    String Tablas_Sql = "poblacion,codigo_postal";
    int BanderaValidarCombos = 0;
    //---------------Jasper Report
    Conexion Con = new Conexion();
    Connection Conectar = Con.Conexion();
    JasperReport Jr = null;
    JasperPrint Jp = null;
    JasperViewer Jv = null;
    String Patch = "";

    public F_Poblacion() {
        initComponents();
        ValidarBanderaBtnNuevo();
        DesHabilitar();
        Listar();
        //CargarCombo();
        ValidarCombos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtexfield9 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jtexfiel15 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(618, 307));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(618, 307));
        getContentPane().setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setFocusable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(70, 70, 130, 30);

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(70, 70, 150, 30);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("REPORTE");
        jButton3.setToolTipText("Imprimir Datos De La Tabla");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(470, 40, 110, 30);

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("EXPORTAR");
        jButton4.setToolTipText("Exportar Datos De  La Tabla");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(470, 70, 110, 30);

        jButton10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton10.setText("NUEVO");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(470, 100, 110, 30);

        jButton11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton11.setText("MODIFICAR");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(470, 130, 110, 30);

        jButton12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton12.setText("CANCELAR");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(470, 160, 110, 30);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(470, 190, 110, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.setToolTipText("Salir De Esta Ventana");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 220, 110, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("CODIGO POBLACION");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 40, 130, 30);

        jtexfield9.setEditable(false);
        jtexfield9.setFocusable(false);
        getContentPane().add(jtexfield9);
        jtexfield9.setBounds(150, 40, 60, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("POBLACION");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 40, 80, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setFocusable(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 150, 430, 100);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(460, 40, 20, 210);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("BUSCAR");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 120, 90, 30);

        jTextField8.setToolTipText("Puedes Buscar Por Identificacion De La Poblacion,Nombre De La Poblacion Y Por Pais");
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(80, 120, 370, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(30, 110, 410, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("PAIS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 70, 40, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(300, 40, 150, 30);

        jtexfiel15.setEditable(false);
        jtexfiel15.setFocusable(false);
        getContentPane().add(jtexfiel15);
        jtexfiel15.setBounds(80, 70, 60, 30);

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "POBLACION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 580, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "¿Desea Generar Reporte?", "Reporte", JOptionPane.YES_NO_OPTION);

        if (i == JOptionPane.YES_OPTION) {

            CrearReporte();
            VisualizarReporte();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String AuxBtn = jButton10.getText();
        if (AuxBtn.equals("NUEVO")) {
            BanderaNuevo = true;
            Habilitar();

        } else {
            BanderaNuevo = false;
            DesHabilitar();
        }

//        Limpiar();
//        Habilitar();
        ComprobarBtn();

        ValidarBanderaBtnNuevo();

        //        Grabar();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Modificar();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Limpiar();
        DesHabilitar();
        BanderaNuevo = false;
        ValidarBanderaBtnNuevo();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Eliminar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        Listar();
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        ObtenerDatosTabla();
        HabilitarTabla();
    }//GEN-LAST:event_jTable1MousePressed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        ObtenerCodigoPostal();
    }//GEN-LAST:event_jComboBox2ItemStateChanged
    //--------------METODOS JASPER

    public void CrearReporte() {

        Patch = "C:\\TesoCartera\\src\\Reportes\\Report_Poblacion.jasper";
        try {

            Jr = (JasperReport) JRLoader.loadObjectFromFile(Patch);
            Jp = JasperFillManager.fillReport(Jr, null, Conectar);

        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Error En Ejecucion De Jasper: " + e);
        }
    }

    public void VisualizarReporte() {

        Jv = new JasperViewer(Jp, false);
        Jv.setVisible(true);
        Jv.setTitle("PAISES REGISTRADOS");
    }

    //--------------------------------
    void ValidarCombos() {

        if (BanderaValidarCombos == 1) {

            CargarCombo();
        } else {

            System.out.println("Bandera igual a 0");
        }
    }

    //--------------------------------

    void ValidarBanderaBtnNuevo() {

        if (BanderaNuevo == false) {
            jButton10.setText("NUEVO");
        } else {
            jButton10.setText("GRABAR");
        }

    }

    void ComprobarBtn() {

        String Aux = jButton10.getText();

        if (Aux.equals("NUEVO")) {

            Limpiar();
            ObtenerConsecutivo();
        } else {

            if (!jTextField2.getText().equals("") && !jTextField1.getText().equals("")) {
                Grabar();
            } else {
                JOptionPane.showMessageDialog(this, "Verifique Que Los Campos Pais Y Poblacion No Esten Vacios", "Verificar", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    void Grabar() {

        mcp.setIdCodPostal(Integer.parseInt(jtexfiel15.getText()));
        //mp.setIdPoblacion(Integer.parseInt(jtexfield9.getText()));
        mp.setNombrePoblacion(jTextField2.getText());

        SentenciaSql = "NULL,'" + mp.getNombrePoblacion() + "' , '" + mcp.getIdCodPostal() + "'";
        m.Grabar(TablaSql, SentenciaSql);

        Limpiar();
        Listar();

    }

    void Modificar() {
        mcp.setIdCodPostal(Integer.parseInt(jtexfiel15.getText()));
        mp.setNombrePoblacion(jTextField2.getText());
        mp.setIdPoblacion(Integer.parseInt(jtexfield9.getText()));

        SentenciaSql = "nombre_poblacion='" + mp.getNombrePoblacion() + "',id_codigo_postal='" + mcp.getIdCodPostal() + "' where id_poblacion='" + mp.getIdPoblacion() + "'";
        m.Modificar(TablaSql, SentenciaSql);
        Limpiar();
        Listar();
    }

    void Eliminar() {
        mp.setIdPoblacion(Integer.parseInt(jtexfield9.getText()));
        SentenciaSql = "id_poblacion = '" + mp.getIdPoblacion() + "'";

        System.out.println("id = " + mcp.getIdCodPostal());
        m.Eliminar(TablaSql, SentenciaSql);
        Limpiar();
        Listar();
    }

    void Listar() {
        FiltroSql = jTextField8.getText();
        String Sql = "select poblacion.id_poblacion,poblacion.nombre_poblacion,poblacion.id_codigo_postal,"
                + "codigo_postal.nombre_pais from " + Tablas_Sql + " where poblacion.id_codigo_postal=codigo_postal.id_cod_postal "
                + "&& concat(poblacion.id_poblacion,poblacion.nombre_poblacion,codigo_postal.nombre_pais) like '%" + FiltroSql + "%'"
                + " order by id_poblacion asc";
        m.Listar(Sql, jTable1);

    }

    void Limpiar() {

        m.LimpiarJText(jtexfield9);
        m.LimpiarJText(jTextField2);
        m.LimpiarJText(jTextField8);
        m.LimpiarJText(jTextField1);
    }

    void ObtenerConsecutivo() {

        // m.ObtenerConsecutivo("codigo_postal", "id_cod_postal", jtexfield9);
        jtexfield9.setText("");
    }

    void ObtenerDatosTabla() {
        int Fila = jTable1.getSelectedRow();
        m.ObtenerDatoTabla(jTable1, Fila, jtexfield9, 0);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField2, 1);
        m.ObtenerDatoTabla(jTable1, Fila, jtexfiel15, 2);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField1, 3);
    }

    void Habilitar() {

        m.HabilitarJText(jTextField2);
        m.HabilitarJText(jTextField2);
        m.HabilitarJCombo(jComboBox2);
        m.DesHabilitarJBtn(jButton11);
        m.HabilitarJBtn(jButton12);
        m.DesHabilitarJBtn(jButton2);
        m.HabilitarJBtn(jButton1);
        jtexfield9.transferFocus();

    }

    void HabilitarTabla() {

        BanderaNuevo = false;
        ValidarBanderaBtnNuevo();
        m.HabilitarJText(jTextField2);
        m.HabilitarJCombo(jComboBox2);
        m.HabilitarJBtn(jButton11);
        m.HabilitarJBtn(jButton12);
        m.HabilitarJBtn(jButton2);
        m.HabilitarJBtn(jButton1);
        jtexfield9.transferFocus();

    }

    void DesHabilitar() {

        jtexfield9.transferFocus();
        m.DesHabilitarJText(jTextField2);
        m.DesHabilitarJCombo(jComboBox2);
        m.DesHabilitarJBtn(jButton11);
        m.DesHabilitarJBtn(jButton12);
        m.DesHabilitarJBtn(jButton2);
        m.HabilitarJBtn(jButton1);

    }

    void ObtenerCodigoPostal() {
        String Delimitador = "]";
        String Aux = (String) jComboBox2.getSelectedItem();
        String[] Separacion = Aux.split(Delimitador);
        jTextField1.setText(Separacion[1]);
        jtexfiel15.setText(Separacion[0]);

    }

    void CargarCombo() {

        // jComboBox2.removeAllItems();
        String Sql = "select * from codigo_postal";
        String IdSql = "id_cod_postal";
        String NombreSql = "nombre_pais";

        m.CargarLIstaComboBox(Sql, IdSql, NombreSql, "]", jComboBox2);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jtexfiel15;
    private javax.swing.JTextField jtexfield9;
    // End of variables declaration//GEN-END:variables
}
