/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Frames;

import Metodos.MetodosGenerales;
import Metodos.MetodosJasper;
import Modelos.Modelo_Producto;
import javax.swing.JOptionPane;

/**
 *
 * @author zlaifer
 */
public class F_Productos extends javax.swing.JInternalFrame {

    String SentenciaSql = null;
    String TablaSql = "producto";
    String FiltroSql = null;
    MetodosGenerales m = new MetodosGenerales();
    Modelos.Modelo_Producto mp = new Modelo_Producto();
    public F_Productos() {
        initComponents();
        DesHabilitar();
        Listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setTitle("PRODUCTOS");
        setMinimumSize(new java.awt.Dimension(940, 421));
        setPreferredSize(new java.awt.Dimension(940, 421));
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("CATEGORIA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(560, 80, 90, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("CODIGO - PRODUCTO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 50, 130, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(160, 50, 180, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(160, 80, 180, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("REFERENCIA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 80, 130, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("REFERENCIA CLIENTE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 110, 130, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(160, 110, 180, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(630, 80, 110, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("U. MEDIDA");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(560, 110, 90, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(630, 110, 110, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----", "GRAMOS", "LITROS", "KILOGRAMOS", "UNIDADES" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(630, 110, 130, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- SELECCIONE UNO ---", "GRANEL", "MATERIAL DE EMPAQUE", "MATERIA PRIMA", "PRODUCTO TERMINADO", "SERVICIO" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(630, 80, 130, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("STOCK ACTUAL");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 110, 100, 30);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(440, 110, 110, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("PRECIO VENTA");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(560, 140, 100, 30);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(460, 140, 90, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setFocusable(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 220, 730, 140);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("REPORTE");
        jButton3.setToolTipText("Imprimir Datos De La Tabla");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(780, 70, 110, 30);

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("EXPORTAR");
        jButton4.setToolTipText("Exportar Datos De  La Tabla");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(780, 100, 110, 30);

        jButton10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton10.setText("NUEVO");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(780, 160, 110, 30);

        jButton11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton11.setText("MODIFICAR");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(780, 220, 110, 30);

        jButton12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton12.setText("CANCELAR");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(780, 250, 110, 30);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(780, 280, 110, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.setToolTipText("Salir De Esta Ventana");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(780, 310, 110, 30);

        jButton13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton13.setText("GRABAR");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(780, 190, 110, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(770, 70, 10, 270);

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(90, 190, 670, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("BUSCAR");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 190, 90, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(30, 180, 730, 10);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("DESCRIPCION");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(350, 50, 120, 30);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(440, 50, 320, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("CODIGO DE BARRAS");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 140, 130, 30);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(160, 140, 180, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("STOCK INICIAL");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(350, 80, 100, 30);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(440, 80, 110, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("PRECIO UNITARIO");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(350, 140, 120, 30);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(660, 140, 100, 30);

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUCTOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 900, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     MetodosJasper Mj = new MetodosJasper();

        int i = JOptionPane.showConfirmDialog(null, "¿Desea Generar Reporte?", "Reporte", JOptionPane.YES_NO_OPTION);

        if (i == JOptionPane.YES_OPTION) {

            if (jTextField2.getText().equals("")) {
                
                Mj.CrearReporte("C:\\TesoCartera\\src\\Reportes\\Report_Productos.jasper", null, null);
                Mj.VisualizarReporte();
            } else {
                Mj.CrearReporte("C:\\TesoCartera\\src\\Reportes\\Report_Producto.jasper", "id_producto", jTextField1.getText());
                Mj.VisualizarReporte();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       
        Limpiar();
        Habilitar();
        jButton1.transferFocus();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        Grabar();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        Listar();
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        HabilitarTabla();
        ObtenerDatosTabla();
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Modificar();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Eliminar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Limpiar();
        DesHabilitar();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        String Combo=jComboBox2.getSelectedItem().toString();
        if (Combo.equals("GRANEL")) {
            jTextField4.setText("GR");
        }
        if (Combo.equals("MATERIAL DE EMPAQUE")) {
            jTextField4.setText("ME");
        }
        if (Combo.equals("MATERIA PRIMA")) {
            jTextField4.setText("MP");
        }
        if (Combo.equals("PRODUCTO TERMINADO")) {
            jTextField4.setText("PT");
        }
        if (Combo.equals("SERVICIO")) {
            jTextField4.setText("SE");
        }
        
        
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String Combo=jComboBox1.getSelectedItem().toString();
        if (Combo.equals("GRAMOS")) {
            jTextField5.setText("GR");
        }
        if (Combo.equals("KILOGRAMOS")) {
            jTextField5.setText("KG");
        }
        if (Combo.equals("LITROS")) {
            jTextField5.setText("LI");
        }
        if (Combo.equals("UNIDADES")) {
            jTextField5.setText("UNI");
        }
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

 void Listar() {
        FiltroSql = jTextField8.getText();
        String Sql = "select * from " + TablaSql + " where concat(id_producto,descripcion_producto) like '%" + FiltroSql + "%'"
                + " order by descripcion_producto asc";
        m.Listar(Sql, jTable1);

    }
 void Grabar() {

        mp.setIdProducto(jTextField1.getText());
        mp.setCodigoBarras(jTextField10.getText());
        mp.setReferenciaProducto(jTextField2.getText());
        mp.setReferenciaProductoCliente(jTextField3.getText());
        mp.setDescripcionCliente(jTextField9.getText());
        mp.setStockInicial(Double.valueOf(jTextField11.getText()));
        mp.setStockActual(Double.valueOf(jTextField6.getText()));
        mp.setPrecioProducto(Double.valueOf(jTextField7.getText()));
        mp.setPrecioProductoVenta(Double.valueOf(jTextField12.getText()));
        mp.setCategoriaProducto(jTextField4.getText());
        mp.setUnidadMedidad(jTextField5.getText());

        SentenciaSql = "'" + mp.getIdProducto()+ "' , '" + mp.getCodigoBarras()+ "' , '" + mp.getReferenciaProducto()+ "' , '" + mp.getReferenciaProductoCliente()
                + "' , '" + mp.getDescripcionCliente()+ "' , '" + mp.getStockInicial()+ "' , '" + mp.getStockActual()+ "' , '" + mp.getPrecioProducto()
                + "' , '" +mp.getPrecioProductoVenta()
                + "' , '" + mp.getCategoriaProducto()+ "' , '" + mp.getUnidadMedidad()+ "'";
        m.Grabar("producto", SentenciaSql);
        
        
        Limpiar();
        Listar();
    }
 void Modificar() {

        mp.setIdProducto(jTextField1.getText());
        mp.setCodigoBarras(jTextField10.getText());
        mp.setReferenciaProducto(jTextField2.getText());
        mp.setReferenciaProductoCliente(jTextField3.getText());
        mp.setDescripcionCliente(jTextField9.getText());
        mp.setStockInicial(Double.valueOf(jTextField11.getText()));
        mp.setStockActual(Double.valueOf(jTextField6.getText()));
        mp.setPrecioProducto(Double.valueOf(jTextField7.getText()));
        mp.setPrecioProductoVenta(Double.valueOf(jTextField12.getText()));
        mp.setCategoriaProducto(jTextField4.getText());
        mp.setUnidadMedidad(jTextField5.getText());

//        SentenciaSql = "'" + mp.getIdProducto()+ "' , '" + mp.getCodigoBarras()+ "' , '" + mp.getReferenciaProducto()+ "' , '" + mp.getReferenciaProductoCliente()
//                + "' , '" + mp.getDescripcionCliente()+ "' , '" + mp.getStockInicial()+ "' , '" + mp.getStockActual()+ "' , '" + mp.getPrecioProducto()
//                + "' , '" + mp.getCategoriaProducto()+ "' , '" + mp.getUnidadMedidad()+ "'";
        
        SentenciaSql = "cod_barras_producto='" + mp.getCodigoBarras()+ "',referencia_producto='" + mp.getReferenciaProducto()+ "', referencia_producto_cliente='" + mp.getReferenciaProductoCliente()
                + "', descripcion_producto='" + mp.getDescripcionCliente()+ "',stock_inicial='" + mp.getStockInicial()+ "' ,stock_actual='" + mp.getStockActual() + "' ,precio_producto='" + mp.getPrecioProducto()
                + "' ,precio_venta_producto='" + mp.getPrecioProductoVenta()
                + "', categoria_producto='" + mp.getCategoriaProducto()+ "' ,unidad_medida='" + mp.getUnidadMedidad()+ "' where id_producto='" + mp.getIdProducto()+ "'";
        m.Modificar("producto", SentenciaSql);
        Limpiar();
        Listar();
    }
 void Eliminar() {
        mp.setIdProducto(jTextField1.getText());
        SentenciaSql = "id_producto = '" + mp.getIdProducto()+ "'";
       
        System.out.println("id = "+mp.getIdProducto());
        m.Eliminar("producto", SentenciaSql);
        Limpiar();
        Listar();
    }
 //--------------------------------
 void ObtenerDatosTabla() {
        int Fila = jTable1.getSelectedRow();
        Limpiar();
        m.ObtenerDatoTabla(jTable1, Fila, jTextField1, 0);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField10, 1);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField2, 2);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField3, 3);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField9, 4);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField11, 5);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField6, 6);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField7, 7);
        
        m.ObtenerDatoTabla(jTable1, Fila, jTextField12, 8);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField4, 9);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField5, 10);
    }

 void Limpiar() {

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField10.setText("");
        jTextField9.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField8.setText("");

    }
 void Habilitar(){
     
     m.HabilitarJText(jTextField1);
     m.HabilitarJText(jTextField2);
     m.HabilitarJText(jTextField3);
     m.HabilitarJText(jTextField10);
     m.HabilitarJText(jTextField9);
     m.HabilitarJText(jTextField11);
     m.HabilitarJText(jTextField12);
     m.HabilitarJText(jTextField6);
     m.DesHabilitarJText(jTextField4);
     m.DesHabilitarJText(jTextField5);
     m.HabilitarJText(jTextField7);
     m.HabilitarJCombo(jComboBox2);
     m.HabilitarJCombo(jComboBox1);
     m.DesHabilitarJBtn(jButton10);
     m.HabilitarJBtn(jButton13);
     m.DesHabilitarJBtn(jButton11);
     m.HabilitarJBtn(jButton12);
     m.DesHabilitarJBtn(jButton2);
     m.HabilitarJBtn(jButton1);
     
 }
 void HabilitarTabla(){
     
     jButton1.transferFocus();
     m.HabilitarJText(jTextField1);
     m.HabilitarJText(jTextField2);
     m.HabilitarJText(jTextField3);
     m.HabilitarJText(jTextField10);
     m.HabilitarJText(jTextField9);
     m.HabilitarJText(jTextField11);
     m.HabilitarJText(jTextField12);
     m.HabilitarJText(jTextField6);
     m.DesHabilitarJText(jTextField4);
     m.DesHabilitarJText(jTextField5);
     m.HabilitarJText(jTextField7);
     m.HabilitarJCombo(jComboBox2);
     m.HabilitarJCombo(jComboBox1);
     m.HabilitarJBtn(jButton10);
     m.DesHabilitarJBtn(jButton13);
     m.HabilitarJBtn(jButton11);
     m.HabilitarJBtn(jButton12);
     m.HabilitarJBtn(jButton2);
     m.HabilitarJBtn(jButton1);
     
 }
 void DesHabilitar(){
     
     m.DesHabilitarJText(jTextField1);
     m.DesHabilitarJText(jTextField2);
     m.DesHabilitarJText(jTextField3);
     m.DesHabilitarJText(jTextField10);
     m.DesHabilitarJText(jTextField9);
     m.DesHabilitarJText(jTextField11);
     m.DesHabilitarJText(jTextField12);
     m.DesHabilitarJText(jTextField6);
     m.DesHabilitarJText(jTextField4);
     m.DesHabilitarJText(jTextField5);
     m.DesHabilitarJText(jTextField7);
     m.DesHabilitarJCombo(jComboBox2);
     m.DesHabilitarJCombo(jComboBox1);
     m.HabilitarJBtn(jButton10);
     m.DesHabilitarJBtn(jButton13);
     m.DesHabilitarJBtn(jButton11);
     m.DesHabilitarJBtn(jButton12);
     m.DesHabilitarJBtn(jButton2);
     m.HabilitarJBtn(jButton1);
     
 }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
