/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Metodos.MetodosGenerales;
import Metodos.MetodosJasper;
import Metodos.FechaActual;
import Modelos.Modelo_CodigoPostal;
import Modelos.Modelo_Poblacion;
import Modelos.Modelo_Provincia;
import Modelos.Modelo_Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author zlaifer
 */
public class F_Usuarios extends javax.swing.JInternalFrame {

    String SentenciaSql = null;
    String TablaSql = "usuario";
    String TablasSql = "usuario,codigo_postal,poblacion,provincia";
    String FiltroSql = null;
    MetodosGenerales m = new MetodosGenerales();
    Metodos.FechaActual fa=new FechaActual();
    Modelos.Modelo_Usuario mu = new Modelo_Usuario();
    Modelos.Modelo_CodigoPostal mcp = new Modelo_CodigoPostal();
    Modelos.Modelo_Poblacion mpo = new Modelo_Poblacion();
    Modelos.Modelo_Provincia mpro = new Modelo_Provincia();
    int BanderaValidarCombos=0;

    public F_Usuarios() {
        initComponents();
        Listar();
//        CargarComboCodPostal();
        JL_Fecha.setText(fa.fecha());
        DesHabilitar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField13 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField15 = new javax.swing.JTextField();
        JT_IdCodPostal = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jTextField16 = new javax.swing.JTextField();
        JT_IdProvincia = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox();
        JT_IdPoblacion = new javax.swing.JTextField();
        JL_Fecha = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTB_Auxiliar = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setTitle("USUARIOS");
        setMinimumSize(new java.awt.Dimension(946, 446));
        setPreferredSize(new java.awt.Dimension(946, 446));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("NICKNAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 200, 120, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 200, 130, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 70, 130, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("CONTRASEÑA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 200, 120, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("DOCUMENTO");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 70, 90, 30);

        jTextField5.setEditable(false);
        jTextField5.setFocusable(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(640, 200, 100, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECCIONE UNO--", "ADMINISTRADOR", "ESTANDAR" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(640, 200, 120, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setFocusable(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 280, 720, 110);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("REPORTE");
        jButton3.setToolTipText("Imprimir Datos De La Tabla");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(790, 80, 110, 30);

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("EXPORTAR");
        jButton4.setToolTipText("Exportar Datos De  La Tabla");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(790, 110, 110, 30);

        jButton10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton10.setText("CREAR");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(790, 170, 110, 30);

        jButton11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton11.setText("MODIFICAR");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(790, 230, 110, 30);

        jButton12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton12.setText("CANCELAR");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(790, 260, 110, 30);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(790, 290, 110, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.setToolTipText("Salir De Esta Ventana");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(790, 320, 110, 30);

        jButton13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton13.setText("GRABAR");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(790, 200, 110, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(780, 50, 10, 340);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("BUSCAR");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 250, 90, 30);

        jPasswordField1.setEditable(false);
        jPasswordField1.setFocusable(false);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(380, 200, 130, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(60, 140, 680, 10);

        jTextField3.setToolTipText("Puedes Buscar Por Identificacion Del Usuario,Nombre Del usuario Y Por Apellido Del Usuario");
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(100, 250, 660, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("DIRECCION");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(290, 100, 90, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("APELLIDOS");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 70, 90, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(370, 70, 150, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("TIPO DOCUMENTO");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 40, 120, 30);

        jTextField6.setEditable(false);
        jTextField6.setFocusable(false);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(150, 40, 110, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- SELECCIONE UNO--", "CEDULA CIUDADANIA", "CEDULA EXTRANJERIA", "PASAPORTE" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(150, 40, 130, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("NOMBRES");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 40, 120, 30);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(370, 40, 150, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("TIPO - USUARIO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 200, 120, 30);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(370, 100, 150, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("F. REGISTRO");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(540, 70, 80, 30);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(620, 40, 140, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("CODIGO  POSTAL");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(40, 150, 110, 30);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("POBLACION");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(290, 150, 90, 30);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("PROVINCIA");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(540, 150, 90, 30);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(60, 240, 680, 20);

        jTextField13.setEditable(false);
        jTextField13.setFocusable(false);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(370, 150, 130, 30);

        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(370, 150, 150, 30);

        jTextField15.setEditable(false);
        jTextField15.setFocusable(false);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(150, 150, 110, 30);

        JT_IdCodPostal.setEditable(false);
        JT_IdCodPostal.setFocusable(false);
        getContentPane().add(JT_IdCodPostal);
        JT_IdCodPostal.setBounds(150, 150, 50, 30);

        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(150, 150, 130, 30);

        jTextField16.setEditable(false);
        jTextField16.setFocusable(false);
        getContentPane().add(jTextField16);
        jTextField16.setBounds(620, 150, 120, 30);

        JT_IdProvincia.setEditable(false);
        JT_IdProvincia.setFocusable(false);
        getContentPane().add(JT_IdProvincia);
        JT_IdProvincia.setBounds(620, 150, 40, 30);

        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(620, 150, 140, 30);

        JT_IdPoblacion.setEditable(false);
        JT_IdPoblacion.setFocusable(false);
        getContentPane().add(JT_IdPoblacion);
        JT_IdPoblacion.setBounds(370, 150, 50, 30);
        getContentPane().add(JL_Fecha);
        JL_Fecha.setBounds(60, 460, 90, 20);

        JTB_Auxiliar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTB_Auxiliar.setFocusable(false);
        jScrollPane2.setViewportView(JTB_Auxiliar);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 450, 880, 120);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("TELEFONO");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(40, 100, 90, 30);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(150, 100, 130, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("EMAIL");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(540, 40, 90, 30);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(620, 70, 140, 30);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(60, 190, 680, 20);

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USUARIOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 910, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MetodosJasper Mj = new MetodosJasper();

        int i = JOptionPane.showConfirmDialog(null, "¿Desea Generar Reporte?", "Reporte", JOptionPane.YES_NO_OPTION);

        if (i == JOptionPane.YES_OPTION) {

            if (jTextField2.getText().equals("")) {
                
                Mj.CrearReporte("C:\\TesoCartera\\src\\Reportes\\Report_Usuarios.jasper", null, null);
                Mj.VisualizarReporte();
            } else {
                Mj.CrearReporte("C:\\TesoCartera\\src\\Reportes\\Report_Usuario.jasper", "id_usuario", jTextField2.getText());
                Mj.VisualizarReporte();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Habilitar();
        jTextField6.transferFocus();
        jPasswordField1.setText("123456");
        BanderaValidarCombos=1;
        ValidarCombos();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        ValidarCampos();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        String Combo = jComboBox2.getSelectedItem().toString();
        if (Combo.equals("CEDULA CIUDADANIA")) {
            jTextField6.setText("C.C");
        }
        if (Combo.equals("CEDULA EXTRANJERIA")) {
            jTextField6.setText("C.E");
        }
        if (Combo.equals("PASAPORTE")) {
            jTextField6.setText("PA");
        }

    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String Combo = jComboBox1.getSelectedItem().toString();
        if (Combo.equals("ADMINISTRADOR")) {
            jTextField5.setText("ADM");
        }
        if (Combo.equals("ESTANDAR")) {
            jTextField5.setText("EST");
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        ObtenerPoblacion();
        CargarComboProvincia();
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        ObtenerCodigoPostal();
        CargarComboPoblacion();
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
        ObtenerProvincia();

    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        Listar();
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        HabilitarTabla();
        ObtenerDatosTabla();
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Modificar();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Eliminar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        DesHabilitar();
        Limpiar();
    }//GEN-LAST:event_jButton12ActionPerformed
    //-------------------------------------------------
    void ValidarCampos(){
        if (!jTextField6.getText().equals("")&&!jTextField2.getText().equals("")&&!jTextField10.getText().equals("")&&!jTextField5.getText().equals("")
                &&!jTextField4.getText().equals("")&&!jTextField8.getText().equals("")&&!jTextField9.getText().equals("")&&!jTextField15.getText().equals("")
                &&!jTextField13.getText().equals("")&&!jTextField16.getText().equals("")&&!jTextField1.getText().equals("")&&!jPasswordField1.getText().equals("")
                &&!jTextField5.getText().equals("")) {
            Grabar();
        }
        JOptionPane.showMessageDialog(this, "Verifique Que Ningun Campo Este Vacio", "Verificar", JOptionPane.ERROR_MESSAGE);
    }
    //-------------------------------------------------
    void ValidarCombos(){
        
        if (BanderaValidarCombos==1) {
        
            CargarComboCodPostal();
        }else{
            
            System.out.println("Bandera igual a 0");
        }
    }
    
    //-------------------------------------------------
    void Listar() {
        FiltroSql = jTextField3.getText();
        String Sql = "select usuario.id_usuario,usuario.tipo_identificacion,usuario.nombres_usuario,usuario.apellidos_usuario,"
                + "codigo_postal.nombre_pais,poblacion.nombre_poblacion,nombre_provincia,usuario.direccion,usuario.telefono_usuario,"
                + "usuario.email_usuario,usuario.nickname,usuario.tipo_usuario,usuario.fecha_registro from " + TablasSql + 
                " where usuario.id_cod_postal=codigo_postal.id_cod_postal && usuario.id_poblacion_usuario=poblacion.id_poblacion "
                + "&& usuario.id_provincia_usuario=provincia.id_provincia "
                + "&& concat(usuario.id_usuario,usuario.nombres_usuario,usuario.apellidos_usuario) like '%" + FiltroSql + "%'"
                + " order by usuario.apellidos_usuario asc";
        m.Listar(Sql, jTable1);
        ListarAuxiliar();

    }
    void ListarAuxiliar() {
        FiltroSql = jTextField3.getText();
        String Sql = "select * from " + TablaSql + " where concat(id_usuario,nombres_usuario,apellidos_usuario) like '%" + FiltroSql + "%'"
                + " order by apellidos_usuario asc";
        m.Listar(Sql, JTB_Auxiliar);

    }

    void CargarComboCodPostal() {

        try {
            String Sql = "select * from codigo_postal";
            String IdSql = "id_cod_postal";
            String NombreSql = "nombre_pais";

            m.CargarLIstaComboBox(Sql, IdSql, NombreSql, "]", jComboBox4);
        } catch (Exception e) {
            System.out.println("Error cargar combopostal");
        }

    }

    void ObtenerCodigoPostal() {

        try {
            String Delimitador = "]";
            String Aux = (String) jComboBox4.getSelectedItem();
            String[] Separacion = Aux.split(Delimitador);
            jTextField15.setText(Separacion[1]);
            JT_IdCodPostal.setText(Separacion[0]);
        } catch (Exception e) {

            System.out.println("Error obtenercodigopostal");
            jTextField15.setText("");
            JT_IdCodPostal.setText("");
        }

    }

    void CargarComboPoblacion() {

        try {
            String Sql = "select * from poblacion where id_codigo_postal='" + JT_IdCodPostal.getText() + "'";
            String IdSql = "id_poblacion";
            String NombreSql = "nombre_poblacion";

            m.CargarLIstaComboBox(Sql, IdSql, NombreSql, "]", jComboBox3);
        } catch (Exception e) {

            System.out.println("Error cargar combo poblacion");
            jComboBox3.removeAllItems();
            jTextField13.setText("");
            JT_IdPoblacion.setText("");
        }
        //ObtenerPoblacion();
    }

    void ObtenerPoblacion() {

        String Delimitador = "]";
        String Aux = (String) jComboBox3.getSelectedItem();

        try {

            String[] Separacion = Aux.split(Delimitador);
            jTextField13.setText(Separacion[1]);
            JT_IdPoblacion.setText(Separacion[0]);
        } catch (Exception e) {
            jTextField13.setText("");
            JT_IdPoblacion.setText("");
        }

    }

    void CargarComboProvincia() {

        try {
            String Sql = "select * from provincia where id_poblacion='" + JT_IdPoblacion.getText() + "'";
            String IdSql = "id_provincia";
            String NombreSql = "nombre_provincia";

            m.CargarLIstaComboBox(Sql, IdSql, NombreSql, "]", jComboBox5);
        } catch (Exception e) {
            System.out.println("Error cargar combo provincia");
            jComboBox5.removeAllItems();
            jTextField16.setText("");
            JT_IdProvincia.setText("");

        }

        // ObtenerProvincia();
    }

    void ObtenerProvincia() {
        try {
            String Delimitador = "]";
            String Aux = (String) jComboBox5.getSelectedItem();
            String[] Separacion = Aux.split(Delimitador);
            jTextField16.setText(Separacion[1]);
            JT_IdProvincia.setText(Separacion[0]);
        } catch (Exception e) {
            jTextField16.setText("");
            JT_IdProvincia.setText("");
        }

    }
    
//------------------------------------------
    void ObtenerDatosTabla(){
        int Fila=jTable1.getSelectedRow();
        
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, jTextField2, 0);
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, jTextField6, 1);
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, jTextField7, 2);
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, jTextField4, 3);
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, JT_IdCodPostal, 4);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField15, 4);
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, JT_IdPoblacion, 5);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField13, 5);
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, JT_IdProvincia, 6);
        m.ObtenerDatoTabla(jTable1, Fila, jTextField16, 6);
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, jTextField8, 7);
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, jTextField10, 8);
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, jTextField9, 9);
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, jTextField1, 10);
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, jPasswordField1, 11);
        m.ObtenerDatoTabla(JTB_Auxiliar, Fila, jTextField5, 12);
        m.ObtenerFechaTabla(JTB_Auxiliar, Fila, jDateChooser1, 13);
    }
//------------------------------------------

    void Grabar() {

        String FechaRegistro;
        mu.setIdUsuario(jTextField2.getText());
        mu.setTipoIdentificacion(jTextField6.getText());
        mu.setNombresUsuario(jTextField7.getText());
        mu.setApellidosUsuario(jTextField4.getText());
        mcp.setIdCodPostal(Integer.parseInt(JT_IdCodPostal.getText()));
//        mcp.setNombrePais(jTextField15.getText());
        mpo.setIdPoblacion(Integer.parseInt(JT_IdPoblacion.getText()));
//        mpo.setNombrePoblacion(jTextField13.getText());
        mpro.setIdProvincia(Integer.parseInt(JT_IdProvincia.getText()));
//        mpro.setNombreProvincia(jTextField16.getText());
        mu.setDireccion(jTextField8.getText());
        mu.setTelefonoUsuario(jTextField8.getText());
        mu.setEmailUsuario(jTextField9.getText());
        mu.setNickname(jTextField1.getText());
        mu.setContrasena(jPasswordField1.getText());
        mu.setTipoUsuario(jTextField5.getText());
        FechaRegistro=m.ConvertirFechaString(jDateChooser1);

        SentenciaSql = "'" + mu.getIdUsuario()+ "','" + mu.getTipoIdentificacion() + "','" + mu.getNombresUsuario()+ "','" 
                + mu.getApellidosUsuario()+ "','"  + mcp.getIdCodPostal() + "','"+ mpo.getIdPoblacion() + "','" + mpro.getIdProvincia() + "','" 
                + mu.getDireccion()+"','"+ mu.getTelefonoUsuario()+"','"+ mu.getEmailUsuario()+ "','" + mu.getNickname()+ "','" 
                + mu.getContrasena()+"','"+ mu.getTipoUsuario()+"','"+FechaRegistro+ "'";

        m.Grabar(TablaSql, SentenciaSql);
        Limpiar();
        Listar();
        DesHabilitar();
    }
    
    void Modificar() {

        String FechaRegistro;
        mu.setIdUsuario(jTextField2.getText());
        mu.setTipoIdentificacion(jTextField6.getText());
        mu.setNombresUsuario(jTextField7.getText());
        mu.setApellidosUsuario(jTextField4.getText());
        mcp.setIdCodPostal(Integer.parseInt(JT_IdCodPostal.getText()));
//        mcp.setNombrePais(jTextField15.getText());
        mpo.setIdPoblacion(Integer.parseInt(JT_IdPoblacion.getText()));
//        mpo.setNombrePoblacion(jTextField13.getText());
        mpro.setIdProvincia(Integer.parseInt(JT_IdProvincia.getText()));
//        mpro.setNombreProvincia(jTextField16.getText());
        mu.setDireccion(jTextField8.getText());
        mu.setTelefonoUsuario(jTextField10.getText());
        mu.setEmailUsuario(jTextField9.getText());
        mu.setNickname(jTextField1.getText());
        mu.setContrasena(jPasswordField1.getText());
        mu.setTipoUsuario(jTextField5.getText());
        FechaRegistro=m.ConvertirFechaString(jDateChooser1);
        
        
        
        SentenciaSql = "tipo_identificacion='" + mu.getTipoIdentificacion()+ "',nombres_usuario='" + mu.getNombresUsuario()
                + "', apellidos_usuario='" + mu.getApellidosUsuario()+ "', id_cod_postal='" + mcp.getIdCodPostal()
                + "',id_poblacion_usuario='" + mpo.getIdPoblacion()+ "' ,id_provincia_usuario='" + mpro.getIdProvincia()
                + "' ,direccion='"+ mu.getDireccion()+"' ,telefono_usuario='" +mu.getTelefonoUsuario()+"' ,email_usuario='" +mu.getEmailUsuario()
                +"' ,nickname='" +mu.getNickname()+"' ,contrasena='" +mu.getContrasena()+"' ,tipo_usuario='" +mu.getTipoUsuario()
                +"' ,fecha_registro='" +FechaRegistro+  "' where id_usuario='" + mu.getIdUsuario()+ "'";

        System.out.println("Sql: " + SentenciaSql);
        m.Modificar(TablaSql, SentenciaSql);
        Limpiar();
        DesHabilitar();
        Listar();
    }
    void Eliminar() {
        mu.setIdUsuario(jTextField2.getText());
        SentenciaSql = "id_usuario = " + mu.getIdUsuario();
        m.Eliminar(TablaSql, SentenciaSql);

        Limpiar();
        DesHabilitar();
        Listar();
    }
    //---------------------------------
     void Limpiar() {
        m.LimpiarJText(JT_IdCodPostal);
        m.LimpiarJText(JT_IdPoblacion);
        m.LimpiarJText(JT_IdProvincia);
        m.LimpiarJText(jTextField6);
        m.LimpiarJText(jTextField2);
        m.LimpiarJText(jTextField10);
        m.LimpiarJText(jTextField7);
        m.LimpiarJText(jTextField4);
        m.LimpiarJText(jTextField8);
        m.LimpiarJText(jTextField9);
        m.LimpiarJText(jTextField15);
        m.LimpiarJText(jTextField13);
        m.LimpiarJText(jTextField16);
        m.LimpiarJText(jTextField1);
        m.LimpiarJText(jPasswordField1);
        m.LimpiarJText(jTextField5);
        m.LimpiarJDate(jDateChooser1);
    }
     void Habilitar(){
     
     m.HabilitarJText(jTextField2);
     m.HabilitarJText(jTextField10);
     m.HabilitarJText(jTextField7);
     m.HabilitarJText(jTextField4);
     m.HabilitarJText(jTextField8);
     m.HabilitarJText(jTextField9);
     m.HabilitarJText(jTextField1);
     m.HabilitarJDate(jDateChooser1);
     m.HabilitarJCombo(jComboBox2);
     m.HabilitarJCombo(jComboBox4);
     m.HabilitarJCombo(jComboBox3);
     m.HabilitarJCombo(jComboBox3);
     m.HabilitarJCombo(jComboBox5);
     m.HabilitarJCombo(jComboBox1);
     
     m.DesHabilitarJBtn(jButton10);
     m.HabilitarJBtn(jButton13);
     m.DesHabilitarJBtn(jButton11);
     m.HabilitarJBtn(jButton12);
     m.DesHabilitarJBtn(jButton2);
     m.HabilitarJBtn(jButton1);
     
 }
     void HabilitarTabla(){
     
     m.HabilitarJText(jTextField2);
     m.HabilitarJText(jTextField10);
     m.HabilitarJText(jTextField7);
     m.HabilitarJText(jTextField4);
     m.HabilitarJText(jTextField8);
     m.HabilitarJText(jTextField9);
     m.HabilitarJText(jTextField1);
     m.HabilitarJDate(jDateChooser1);
     m.HabilitarJCombo(jComboBox2);
     m.HabilitarJCombo(jComboBox4);
     m.HabilitarJCombo(jComboBox3);
     m.HabilitarJCombo(jComboBox3);
     m.HabilitarJCombo(jComboBox5);
     m.HabilitarJCombo(jComboBox1);
     
     m.HabilitarJBtn(jButton10);
     m.DesHabilitarJBtn(jButton13);
     m.HabilitarJBtn(jButton11);
     m.HabilitarJBtn(jButton12);
     m.HabilitarJBtn(jButton2);
     m.HabilitarJBtn(jButton1);
     
 }
     void DesHabilitar(){
     
     m.DesHabilitarJText(jTextField2);
     m.DesHabilitarJText(jTextField10);
     m.DesHabilitarJText(jTextField7);
     m.DesHabilitarJText(jTextField4);
     m.DesHabilitarJText(jTextField8);
     m.DesHabilitarJText(jTextField9);
     m.DesHabilitarJText(jTextField1);
     m.DesHabilitarJDate(jDateChooser1);
     m.DesHabilitarJCombo(jComboBox2);
     m.DesHabilitarJCombo(jComboBox4);
     m.DesHabilitarJCombo(jComboBox3);
     m.DesHabilitarJCombo(jComboBox3);
     m.DesHabilitarJCombo(jComboBox5);
     m.DesHabilitarJCombo(jComboBox1);
     
     m.HabilitarJBtn(jButton10);
     m.DesHabilitarJBtn(jButton13);
     m.DesHabilitarJBtn(jButton11);
     m.DesHabilitarJBtn(jButton12);
     m.DesHabilitarJBtn(jButton2);
     m.HabilitarJBtn(jButton1);
     
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_Fecha;
    private javax.swing.JTable JTB_Auxiliar;
    private javax.swing.JTextField JT_IdCodPostal;
    private javax.swing.JTextField JT_IdPoblacion;
    private javax.swing.JTextField JT_IdProvincia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
